#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_ItemAnimLayersBase

#include "Basic.hpp"

#include "ABP_ItemAnimLayersBase_classes.hpp"
#include "ABP_ItemAnimLayersBase_parameters.hpp"


namespace SDK
{

// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "AnimGraph");

	Params::ABP_ItemAnimLayersBase_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.AnimNotify_OnTurnEntered
// (BlueprintCallable, BlueprintEvent)

void UABP_ItemAnimLayersBase_C::AnimNotify_OnTurnEntered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "AnimNotify_OnTurnEntered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.BlueprintThreadSafeUpdateAnimation
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_ItemAnimLayersBase_C::BlueprintThreadSafeUpdateAnimation(float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "BlueprintThreadSafeUpdateAnimation");

	Params::ABP_ItemAnimLayersBase_C_BlueprintThreadSafeUpdateAnimation Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_ItemAnimLayersBase_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "BlueprintUpdateAnimation");

	Params::ABP_ItemAnimLayersBase_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.CanPlayIdleBreak
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UABP_ItemAnimLayersBase_C::CanPlayIdleBreak()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "CanPlayIdleBreak");

	Params::ABP_ItemAnimLayersBase_C_CanPlayIdleBreak Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.ChooseIdleBreakDelayTime
// (Public, BlueprintCallable, BlueprintEvent)

void UABP_ItemAnimLayersBase_C::ChooseIdleBreakDelayTime()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "ChooseIdleBreakDelayTime");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_26543E0745BF53E7E866178E3251B2E0
// (BlueprintEvent)

void UABP_ItemAnimLayersBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_26543E0745BF53E7E866178E3251B2E0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_26543E0745BF53E7E866178E3251B2E0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_514E0CDE429EBAC7D9195F938172BBEF
// (BlueprintEvent)

void UABP_ItemAnimLayersBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_514E0CDE429EBAC7D9195F938172BBEF()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_514E0CDE429EBAC7D9195F938172BBEF");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_521E279F4DB1AB668676D4BFC15FB91F
// (BlueprintEvent)

void UABP_ItemAnimLayersBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_521E279F4DB1AB668676D4BFC15FB91F()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_521E279F4DB1AB668676D4BFC15FB91F");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_76D9B01F4B3A26B8F9D8D083962A946C
// (BlueprintEvent)

void UABP_ItemAnimLayersBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_76D9B01F4B3A26B8F9D8D083962A946C()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_76D9B01F4B3A26B8F9D8D083962A946C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_7986E8D3439A6EE55E2795B1C0046111
// (BlueprintEvent)

void UABP_ItemAnimLayersBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_7986E8D3439A6EE55E2795B1C0046111()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_7986E8D3439A6EE55E2795B1C0046111");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_83B2319E47F88763A4778C92D0A44ECC
// (BlueprintEvent)

void UABP_ItemAnimLayersBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_83B2319E47F88763A4778C92D0A44ECC()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_83B2319E47F88763A4778C92D0A44ECC");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_881779B34EE4104C3131BDB423BD5A39
// (BlueprintEvent)

void UABP_ItemAnimLayersBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_881779B34EE4104C3131BDB423BD5A39()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_881779B34EE4104C3131BDB423BD5A39");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_AF696734464558C5E68175AB6139398B
// (BlueprintEvent)

void UABP_ItemAnimLayersBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_AF696734464558C5E68175AB6139398B()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_AF696734464558C5E68175AB6139398B");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_AFDBC75B411241CB0058AD9AAA097D17
// (BlueprintEvent)

void UABP_ItemAnimLayersBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_AFDBC75B411241CB0058AD9AAA097D17()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_AFDBC75B411241CB0058AD9AAA097D17");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_B67C2FCC46A03C0AAE2419A1E8FBC0D3
// (BlueprintEvent)

void UABP_ItemAnimLayersBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_B67C2FCC46A03C0AAE2419A1E8FBC0D3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_B67C2FCC46A03C0AAE2419A1E8FBC0D3");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_B9DA04C94E2C96F9009A109E8C5EA461
// (BlueprintEvent)

void UABP_ItemAnimLayersBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_B9DA04C94E2C96F9009A109E8C5EA461()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_B9DA04C94E2C96F9009A109E8C5EA461");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_C04FD0A44244FACA801276A6E8A00D3E
// (BlueprintEvent)

void UABP_ItemAnimLayersBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_C04FD0A44244FACA801276A6E8A00D3E()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_C04FD0A44244FACA801276A6E8A00D3E");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_C203AD70413BF9C4590D8EB5731404CB
// (BlueprintEvent)

void UABP_ItemAnimLayersBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_C203AD70413BF9C4590D8EB5731404CB()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_C203AD70413BF9C4590D8EB5731404CB");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_F38C25404E18B7DD52703594927F29AB
// (BlueprintEvent)

void UABP_ItemAnimLayersBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_F38C25404E18B7DD52703594927F29AB()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_F38C25404E18B7DD52703594927F29AB");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_FBAA047741824C8230242F87B53E3DE5
// (BlueprintEvent)

void UABP_ItemAnimLayersBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_FBAA047741824C8230242F87B53E3DE5()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_BlendListByBool_FBAA047741824C8230242F87B53E3DE5");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_OrientationWarping_0360503341CD303D68696F89F551B727
// (BlueprintEvent)

void UABP_ItemAnimLayersBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_OrientationWarping_0360503341CD303D68696F89F551B727()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_OrientationWarping_0360503341CD303D68696F89F551B727");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_OrientationWarping_57991B654CEF362AFEE678A86133B20D
// (BlueprintEvent)

void UABP_ItemAnimLayersBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_OrientationWarping_57991B654CEF362AFEE678A86133B20D()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_OrientationWarping_57991B654CEF362AFEE678A86133B20D");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_OrientationWarping_9B0FE8DA4F666574A528FA9AF81263F7
// (BlueprintEvent)

void UABP_ItemAnimLayersBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_OrientationWarping_9B0FE8DA4F666574A528FA9AF81263F7()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_OrientationWarping_9B0FE8DA4F666574A528FA9AF81263F7");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_OrientationWarping_DC1A24984F4AD042820B87BE906902B5
// (BlueprintEvent)

void UABP_ItemAnimLayersBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_OrientationWarping_DC1A24984F4AD042820B87BE906902B5()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_OrientationWarping_DC1A24984F4AD042820B87BE906902B5");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_StrideWarping_476774114636081E8B6DE79164CE4B7F
// (BlueprintEvent)

void UABP_ItemAnimLayersBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_StrideWarping_476774114636081E8B6DE79164CE4B7F()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_StrideWarping_476774114636081E8B6DE79164CE4B7F");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_StrideWarping_543CE93D4D84EFC6DF5223B2BF481E23
// (BlueprintEvent)

void UABP_ItemAnimLayersBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_StrideWarping_543CE93D4D84EFC6DF5223B2BF481E23()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_StrideWarping_543CE93D4D84EFC6DF5223B2BF481E23");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_StrideWarping_898F011B45527CA1886DB4BE34C7589B
// (BlueprintEvent)

void UABP_ItemAnimLayersBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_StrideWarping_898F011B45527CA1886DB4BE34C7589B()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_StrideWarping_898F011B45527CA1886DB4BE34C7589B");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_StrideWarping_BBBF709A4ED16448CFD496A35D5AD62E
// (BlueprintEvent)

void UABP_ItemAnimLayersBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_StrideWarping_BBBF709A4ED16448CFD496A35D5AD62E()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_StrideWarping_BBBF709A4ED16448CFD496A35D5AD62E");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_TransitionResult_0A220FFE4F7D733D01E0CBBDE4462053
// (BlueprintEvent)

void UABP_ItemAnimLayersBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_TransitionResult_0A220FFE4F7D733D01E0CBBDE4462053()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_TransitionResult_0A220FFE4F7D733D01E0CBBDE4462053");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_TransitionResult_2C0D52ED45B9D58CA842CCA75B76597E
// (BlueprintEvent)

void UABP_ItemAnimLayersBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_TransitionResult_2C0D52ED45B9D58CA842CCA75B76597E()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_TransitionResult_2C0D52ED45B9D58CA842CCA75B76597E");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_TransitionResult_3CFAEDAA41FFBF21608BB384B7E776A6
// (BlueprintEvent)

void UABP_ItemAnimLayersBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_TransitionResult_3CFAEDAA41FFBF21608BB384B7E776A6()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_TransitionResult_3CFAEDAA41FFBF21608BB384B7E776A6");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_TransitionResult_4C7E090C465247DA5CE058969144CA48
// (BlueprintEvent)

void UABP_ItemAnimLayersBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_TransitionResult_4C7E090C465247DA5CE058969144CA48()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_TransitionResult_4C7E090C465247DA5CE058969144CA48");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_TransitionResult_79B4274D424BB23F214B4EA45BD8EB8B
// (BlueprintEvent)

void UABP_ItemAnimLayersBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_TransitionResult_79B4274D424BB23F214B4EA45BD8EB8B()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_TransitionResult_79B4274D424BB23F214B4EA45BD8EB8B");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_TransitionResult_8EBFADA9496083A223A49D8387378B42
// (BlueprintEvent)

void UABP_ItemAnimLayersBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_TransitionResult_8EBFADA9496083A223A49D8387378B42()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_TransitionResult_8EBFADA9496083A223A49D8387378B42");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_TransitionResult_AD5F8EFD4F55B140A13A30811192AC4F
// (BlueprintEvent)

void UABP_ItemAnimLayersBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_TransitionResult_AD5F8EFD4F55B140A13A30811192AC4F()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_TransitionResult_AD5F8EFD4F55B140A13A30811192AC4F");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_TransitionResult_AF82080AA1491A48A7C29F8DC2727574
// (BlueprintEvent)

void UABP_ItemAnimLayersBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_TransitionResult_AF82080AA1491A48A7C29F8DC2727574()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_TransitionResult_AF82080AA1491A48A7C29F8DC2727574");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_TransitionResult_C202D18D4CE9E226BEED5E8A9E316840
// (BlueprintEvent)

void UABP_ItemAnimLayersBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_TransitionResult_C202D18D4CE9E226BEED5E8A9E316840()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_TransitionResult_C202D18D4CE9E226BEED5E8A9E316840");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_TransitionResult_C375910043055A03AD1C3296E9CCDB91
// (BlueprintEvent)

void UABP_ItemAnimLayersBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_TransitionResult_C375910043055A03AD1C3296E9CCDB91()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ItemAnimLayersBase_AnimGraphNode_TransitionResult_C375910043055A03AD1C3296E9CCDB91");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.ExecuteUbergraph_ABP_ItemAnimLayersBase
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_ItemAnimLayersBase_C::ExecuteUbergraph_ABP_ItemAnimLayersBase(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "ExecuteUbergraph_ABP_ItemAnimLayersBase");

	Params::ABP_ItemAnimLayersBase_C_ExecuteUbergraph_ABP_ItemAnimLayersBase Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.FullBody_Aiming
// (HasOutParams, BlueprintCallable)
// Parameters:
// const struct FPoseLink&                 PreAimPose                                             (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// double                                  AimYaw_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  AimPitch_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FPoseLink*                       FullBody_Aiming_0                                      (Parm, OutParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::FullBody_Aiming(const struct FPoseLink& PreAimPose, double AimYaw_0, double AimPitch_0, struct FPoseLink* FullBody_Aiming_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "FullBody_Aiming");

	Params::ABP_ItemAnimLayersBase_C_FullBody_Aiming Parms{};

	Parms.PreAimPose = std::move(PreAimPose);
	Parms.AimYaw_0 = AimYaw_0;
	Parms.AimPitch_0 = AimPitch_0;

	UObject::ProcessEvent(Func, &Parms);

	if (FullBody_Aiming_0 != nullptr)
		*FullBody_Aiming_0 = std::move(Parms.FullBody_Aiming_0);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.FullBody_CycleState
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink*                       FullBody_CycleState_0                                  (Parm, OutParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::FullBody_CycleState(struct FPoseLink* FullBody_CycleState_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "FullBody_CycleState");

	Params::ABP_ItemAnimLayersBase_C_FullBody_CycleState Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (FullBody_CycleState_0 != nullptr)
		*FullBody_CycleState_0 = std::move(Parms.FullBody_CycleState_0);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.FullBody_Dash
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink*                       FullBody_Dash_0                                        (Parm, OutParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::FullBody_Dash(struct FPoseLink* FullBody_Dash_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "FullBody_Dash");

	Params::ABP_ItemAnimLayersBase_C_FullBody_Dash Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (FullBody_Dash_0 != nullptr)
		*FullBody_Dash_0 = std::move(Parms.FullBody_Dash_0);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.FullBody_DoubleJump
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink*                       FullBody_DoubleJump_0                                  (Parm, OutParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::FullBody_DoubleJump(struct FPoseLink* FullBody_DoubleJump_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "FullBody_DoubleJump");

	Params::ABP_ItemAnimLayersBase_C_FullBody_DoubleJump Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (FullBody_DoubleJump_0 != nullptr)
		*FullBody_DoubleJump_0 = std::move(Parms.FullBody_DoubleJump_0);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.FullBody_EntryState
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink*                       FullBody_EntryState_0                                  (Parm, OutParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::FullBody_EntryState(struct FPoseLink* FullBody_EntryState_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "FullBody_EntryState");

	Params::ABP_ItemAnimLayersBase_C_FullBody_EntryState Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (FullBody_EntryState_0 != nullptr)
		*FullBody_EntryState_0 = std::move(Parms.FullBody_EntryState_0);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.FullBody_FallLandState
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink*                       FullBody_FallLandState_0                               (Parm, OutParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::FullBody_FallLandState(struct FPoseLink* FullBody_FallLandState_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "FullBody_FallLandState");

	Params::ABP_ItemAnimLayersBase_C_FullBody_FallLandState Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (FullBody_FallLandState_0 != nullptr)
		*FullBody_FallLandState_0 = std::move(Parms.FullBody_FallLandState_0);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.FullBody_FallLoopState
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink*                       FullBody_FallLoopState_0                               (Parm, OutParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::FullBody_FallLoopState(struct FPoseLink* FullBody_FallLoopState_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "FullBody_FallLoopState");

	Params::ABP_ItemAnimLayersBase_C_FullBody_FallLoopState Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (FullBody_FallLoopState_0 != nullptr)
		*FullBody_FallLoopState_0 = std::move(Parms.FullBody_FallLoopState_0);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.FullBody_IdleState
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink*                       FullBody_IdleState_0                                   (Parm, OutParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::FullBody_IdleState(struct FPoseLink* FullBody_IdleState_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "FullBody_IdleState");

	Params::ABP_ItemAnimLayersBase_C_FullBody_IdleState Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (FullBody_IdleState_0 != nullptr)
		*FullBody_IdleState_0 = std::move(Parms.FullBody_IdleState_0);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.FullBody_JumpApexState
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink*                       FullBody_JumpApexState_0                               (Parm, OutParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::FullBody_JumpApexState(struct FPoseLink* FullBody_JumpApexState_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "FullBody_JumpApexState");

	Params::ABP_ItemAnimLayersBase_C_FullBody_JumpApexState Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (FullBody_JumpApexState_0 != nullptr)
		*FullBody_JumpApexState_0 = std::move(Parms.FullBody_JumpApexState_0);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.FullBody_JumpStartLoopState
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink*                       FullBody_JumpStartLoopState_0                          (Parm, OutParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::FullBody_JumpStartLoopState(struct FPoseLink* FullBody_JumpStartLoopState_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "FullBody_JumpStartLoopState");

	Params::ABP_ItemAnimLayersBase_C_FullBody_JumpStartLoopState Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (FullBody_JumpStartLoopState_0 != nullptr)
		*FullBody_JumpStartLoopState_0 = std::move(Parms.FullBody_JumpStartLoopState_0);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.FullBody_JumpStartState
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink*                       FullBody_JumpStartState_0                              (Parm, OutParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::FullBody_JumpStartState(struct FPoseLink* FullBody_JumpStartState_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "FullBody_JumpStartState");

	Params::ABP_ItemAnimLayersBase_C_FullBody_JumpStartState Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (FullBody_JumpStartState_0 != nullptr)
		*FullBody_JumpStartState_0 = std::move(Parms.FullBody_JumpStartState_0);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.FullBody_PivotState
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink*                       FullBody_PivotState_0                                  (Parm, OutParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::FullBody_PivotState(struct FPoseLink* FullBody_PivotState_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "FullBody_PivotState");

	Params::ABP_ItemAnimLayersBase_C_FullBody_PivotState Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (FullBody_PivotState_0 != nullptr)
		*FullBody_PivotState_0 = std::move(Parms.FullBody_PivotState_0);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.FullBody_SkeletalControls
// (HasOutParams, BlueprintCallable)
// Parameters:
// const struct FPoseLink&                 InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink*                       FullBody_SkeletalControls_0                            (Parm, OutParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::FullBody_SkeletalControls(const struct FPoseLink& InPose, struct FPoseLink* FullBody_SkeletalControls_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "FullBody_SkeletalControls");

	Params::ABP_ItemAnimLayersBase_C_FullBody_SkeletalControls Parms{};

	Parms.InPose = std::move(InPose);

	UObject::ProcessEvent(Func, &Parms);

	if (FullBody_SkeletalControls_0 != nullptr)
		*FullBody_SkeletalControls_0 = std::move(Parms.FullBody_SkeletalControls_0);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.FullBody_SlideInState
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink*                       FullBody_SlideInState_0                                (Parm, OutParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::FullBody_SlideInState(struct FPoseLink* FullBody_SlideInState_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "FullBody_SlideInState");

	Params::ABP_ItemAnimLayersBase_C_FullBody_SlideInState Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (FullBody_SlideInState_0 != nullptr)
		*FullBody_SlideInState_0 = std::move(Parms.FullBody_SlideInState_0);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.FullBody_SlideLoopState
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink*                       FullBody_SlideLoopState_0                              (Parm, OutParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::FullBody_SlideLoopState(struct FPoseLink* FullBody_SlideLoopState_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "FullBody_SlideLoopState");

	Params::ABP_ItemAnimLayersBase_C_FullBody_SlideLoopState Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (FullBody_SlideLoopState_0 != nullptr)
		*FullBody_SlideLoopState_0 = std::move(Parms.FullBody_SlideLoopState_0);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.FullBody_SlideOutState
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink*                       FullBody_SlideOutState_0                               (Parm, OutParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::FullBody_SlideOutState(struct FPoseLink* FullBody_SlideOutState_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "FullBody_SlideOutState");

	Params::ABP_ItemAnimLayersBase_C_FullBody_SlideOutState Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (FullBody_SlideOutState_0 != nullptr)
		*FullBody_SlideOutState_0 = std::move(Parms.FullBody_SlideOutState_0);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.FullBody_StartState
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink*                       FullBody_StartState_0                                  (Parm, OutParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::FullBody_StartState(struct FPoseLink* FullBody_StartState_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "FullBody_StartState");

	Params::ABP_ItemAnimLayersBase_C_FullBody_StartState Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (FullBody_StartState_0 != nullptr)
		*FullBody_StartState_0 = std::move(Parms.FullBody_StartState_0);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.FullBody_StopState
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink*                       FullBody_StopState_0                                   (Parm, OutParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::FullBody_StopState(struct FPoseLink* FullBody_StopState_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "FullBody_StopState");

	Params::ABP_ItemAnimLayersBase_C_FullBody_StopState Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (FullBody_StopState_0 != nullptr)
		*FullBody_StopState_0 = std::move(Parms.FullBody_StopState_0);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.FullBodyAdditives
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink*                       FullBodyAdditives_0                                    (Parm, OutParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::FullBodyAdditives(struct FPoseLink* FullBodyAdditives_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "FullBodyAdditives");

	Params::ABP_ItemAnimLayersBase_C_FullBodyAdditives Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (FullBodyAdditives_0 != nullptr)
		*FullBodyAdditives_0 = std::move(Parms.FullBodyAdditives_0);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.GetDesiredPivotSequence
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// EAnimEnum_CardinalDirection             InDirection                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UAnimSequenceBase*                ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)

class UAnimSequenceBase* UABP_ItemAnimLayersBase_C::GetDesiredPivotSequence(EAnimEnum_CardinalDirection InDirection)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "GetDesiredPivotSequence");

	Params::ABP_ItemAnimLayersBase_C_GetDesiredPivotSequence Parms{};

	Parms.InDirection = InDirection;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.GetLeftHandSocketLocation
// (Public, BlueprintCallable, BlueprintEvent)

void UABP_ItemAnimLayersBase_C::GetLeftHandSocketLocation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "GetLeftHandSocketLocation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.GetMainAnimBPThreadSafe
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UABP_Mannequin_Base_C*            ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)

class UABP_Mannequin_Base_C* UABP_ItemAnimLayersBase_C::GetMainAnimBPThreadSafe()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "GetMainAnimBPThreadSafe");

	Params::ABP_ItemAnimLayersBase_C_GetMainAnimBPThreadSafe Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.GetMainPlayerBP
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class ABP_PlayerCharacter_C*            ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)

class ABP_PlayerCharacter_C* UABP_ItemAnimLayersBase_C::GetMainPlayerBP()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "GetMainPlayerBP");

	Params::ABP_ItemAnimLayersBase_C_GetMainPlayerBP Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.GetMovementComponent
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UCharacterMovementComponent*      ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UCharacterMovementComponent* UABP_ItemAnimLayersBase_C::GetMovementComponent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "GetMovementComponent");

	Params::ABP_ItemAnimLayersBase_C_GetMovementComponent Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.Head_FaceLayer
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink*                       Head_FaceLayer_0                                       (Parm, OutParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::Head_FaceLayer(struct FPoseLink* Head_FaceLayer_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "Head_FaceLayer");

	Params::ABP_ItemAnimLayersBase_C_Head_FaceLayer Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Head_FaceLayer_0 != nullptr)
		*Head_FaceLayer_0 = std::move(Parms.Head_FaceLayer_0);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.Land Recovery Start
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FAnimUpdateContext&        Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FAnimNodeReference&        Node                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::Land_Recovery_Start(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "Land Recovery Start");

	Params::ABP_ItemAnimLayersBase_C_Land_Recovery_Start Parms{};

	Parms.Context = std::move(Context);
	Parms.Node = std::move(Node);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.LeftHandPose_OverrideState
// (HasOutParams, BlueprintCallable)
// Parameters:
// const struct FPoseLink&                 InputPose                                              (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink*                       LeftHandPose_OverrideState_0                           (Parm, OutParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::LeftHandPose_OverrideState(const struct FPoseLink& InputPose, struct FPoseLink* LeftHandPose_OverrideState_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "LeftHandPose_OverrideState");

	Params::ABP_ItemAnimLayersBase_C_LeftHandPose_OverrideState Parms{};

	Parms.InputPose = std::move(InputPose);

	UObject::ProcessEvent(Func, &Parms);

	if (LeftHandPose_OverrideState_0 != nullptr)
		*LeftHandPose_OverrideState_0 = std::move(Parms.LeftHandPose_OverrideState_0);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.OnInitialUpdate
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FAnimUpdateContext&        Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FAnimNodeReference&        Node                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::OnInitialUpdate(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "OnInitialUpdate");

	Params::ABP_ItemAnimLayersBase_C_OnInitialUpdate Parms{};

	Parms.Context = std::move(Context);
	Parms.Node = std::move(Node);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.OnRelevantTurnInPlacePlayer
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FAnimUpdateContext&        Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FAnimNodeReference&        Node                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::OnRelevantTurnInPlacePlayer(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "OnRelevantTurnInPlacePlayer");

	Params::ABP_ItemAnimLayersBase_C_OnRelevantTurnInPlacePlayer Parms{};

	Parms.Context = std::move(Context);
	Parms.Node = std::move(Node);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.OnUpdate
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FAnimUpdateContext&        Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FAnimNodeReference&        Node                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::OnUpdate(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "OnUpdate");

	Params::ABP_ItemAnimLayersBase_C_OnUpdate Parms{};

	Parms.Context = std::move(Context);
	Parms.Node = std::move(Node);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.OnUpdateTurnInPlaceEvaluator
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FAnimUpdateContext&        Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FAnimNodeReference&        Node                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::OnUpdateTurnInPlaceEvaluator(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "OnUpdateTurnInPlaceEvaluator");

	Params::ABP_ItemAnimLayersBase_C_OnUpdateTurnInPlaceEvaluator Parms{};

	Parms.Context = std::move(Context);
	Parms.Node = std::move(Node);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.ProcessIdleBreakTransitionLogic
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_ItemAnimLayersBase_C::ProcessIdleBreakTransitionLogic(double DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "ProcessIdleBreakTransitionLogic");

	Params::ABP_ItemAnimLayersBase_C_ProcessIdleBreakTransitionLogic Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.ResetIdleBreakTransitionLogic
// (Public, BlueprintCallable, BlueprintEvent)

void UABP_ItemAnimLayersBase_C::ResetIdleBreakTransitionLogic()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "ResetIdleBreakTransitionLogic");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.SelectTurnInPlaceAnimation
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// double                                  Direction                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UAnimSequence**                   Result                                                 (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UABP_ItemAnimLayersBase_C::SelectTurnInPlaceAnimation(double Direction, class UAnimSequence** Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "SelectTurnInPlaceAnimation");

	Params::ABP_ItemAnimLayersBase_C_SelectTurnInPlaceAnimation Parms{};

	Parms.Direction = Direction;

	UObject::ProcessEvent(Func, &Parms);

	if (Result != nullptr)
		*Result = Parms.Result;
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.SetHandIK
// (Public, BlueprintCallable, BlueprintEvent)

void UABP_ItemAnimLayersBase_C::SetHandIK()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "SetHandIK");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.SetLeftHandPoseOverrideWeight
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FAnimUpdateContext&        Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FAnimNodeReference&        Node                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::SetLeftHandPoseOverrideWeight(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "SetLeftHandPoseOverrideWeight");

	Params::ABP_ItemAnimLayersBase_C_SetLeftHandPoseOverrideWeight Parms{};

	Parms.Context = std::move(Context);
	Parms.Node = std::move(Node);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.SetUpDashStartAnim
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FAnimUpdateContext&        Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FAnimNodeReference&        Node                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::SetUpDashStartAnim(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "SetUpDashStartAnim");

	Params::ABP_ItemAnimLayersBase_C_SetUpDashStartAnim Parms{};

	Parms.Context = std::move(Context);
	Parms.Node = std::move(Node);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.SetupEntryStateAnim
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FAnimUpdateContext&        Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FAnimNodeReference&        Node                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::SetupEntryStateAnim(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "SetupEntryStateAnim");

	Params::ABP_ItemAnimLayersBase_C_SetupEntryStateAnim Parms{};

	Parms.Context = std::move(Context);
	Parms.Node = std::move(Node);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.SetupFallLandAnim
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FAnimUpdateContext&        Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FAnimNodeReference&        Node                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::SetupFallLandAnim(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "SetupFallLandAnim");

	Params::ABP_ItemAnimLayersBase_C_SetupFallLandAnim Parms{};

	Parms.Context = std::move(Context);
	Parms.Node = std::move(Node);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.SetUpHitReactionAnim
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FAnimUpdateContext&        Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FAnimNodeReference&        Node                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::SetUpHitReactionAnim(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "SetUpHitReactionAnim");

	Params::ABP_ItemAnimLayersBase_C_SetUpHitReactionAnim Parms{};

	Parms.Context = std::move(Context);
	Parms.Node = std::move(Node);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.SetUpIdleBreakAnim
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FAnimUpdateContext&        Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FAnimNodeReference&        Node                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::SetUpIdleBreakAnim(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "SetUpIdleBreakAnim");

	Params::ABP_ItemAnimLayersBase_C_SetUpIdleBreakAnim Parms{};

	Parms.Context = std::move(Context);
	Parms.Node = std::move(Node);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.SetUpIdleState
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FAnimUpdateContext&        Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FAnimNodeReference&        Node                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::SetUpIdleState(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "SetUpIdleState");

	Params::ABP_ItemAnimLayersBase_C_SetUpIdleState Parms{};

	Parms.Context = std::move(Context);
	Parms.Node = std::move(Node);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.SetupIdleTransition
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FAnimUpdateContext&        Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FAnimNodeReference&        Node                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::SetupIdleTransition(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "SetupIdleTransition");

	Params::ABP_ItemAnimLayersBase_C_SetupIdleTransition Parms{};

	Parms.Context = std::move(Context);
	Parms.Node = std::move(Node);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.SetUpPivotAnim
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FAnimUpdateContext&        Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FAnimNodeReference&        Node                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::SetUpPivotAnim(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "SetUpPivotAnim");

	Params::ABP_ItemAnimLayersBase_C_SetUpPivotAnim Parms{};

	Parms.Context = std::move(Context);
	Parms.Node = std::move(Node);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.SetUpSlideOutAnim
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FAnimUpdateContext&        Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FAnimNodeReference&        Node                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::SetUpSlideOutAnim(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "SetUpSlideOutAnim");

	Params::ABP_ItemAnimLayersBase_C_SetUpSlideOutAnim Parms{};

	Parms.Context = std::move(Context);
	Parms.Node = std::move(Node);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.SetUpStartAnim
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FAnimUpdateContext&        Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FAnimNodeReference&        Node                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::SetUpStartAnim(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "SetUpStartAnim");

	Params::ABP_ItemAnimLayersBase_C_SetUpStartAnim Parms{};

	Parms.Context = std::move(Context);
	Parms.Node = std::move(Node);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.SetUpStopAnim
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FAnimUpdateContext&        Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FAnimNodeReference&        Node                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::SetUpStopAnim(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "SetUpStopAnim");

	Params::ABP_ItemAnimLayersBase_C_SetUpStopAnim Parms{};

	Parms.Context = std::move(Context);
	Parms.Node = std::move(Node);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.SetupTurnInPlaceRecoveryState
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FAnimUpdateContext&        Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FAnimNodeReference&        Node                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::SetupTurnInPlaceRecoveryState(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "SetupTurnInPlaceRecoveryState");

	Params::ABP_ItemAnimLayersBase_C_SetupTurnInPlaceRecoveryState Parms{};

	Parms.Context = std::move(Context);
	Parms.Node = std::move(Node);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.SetUpTurnInPlaceRotationState
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FAnimUpdateContext&        Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FAnimNodeReference&        Node                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::SetUpTurnInPlaceRotationState(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "SetUpTurnInPlaceRotationState");

	Params::ABP_ItemAnimLayersBase_C_SetUpTurnInPlaceRotationState Parms{};

	Parms.Context = std::move(Context);
	Parms.Node = std::move(Node);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.ShouldDistanceMatchStop
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UABP_ItemAnimLayersBase_C::ShouldDistanceMatchStop()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "ShouldDistanceMatchStop");

	Params::ABP_ItemAnimLayersBase_C_ShouldDistanceMatchStop Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.TurnInPlaceEvaluator
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FAnimUpdateContext&        Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FAnimNodeReference&        Node                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::TurnInPlaceEvaluator(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "TurnInPlaceEvaluator");

	Params::ABP_ItemAnimLayersBase_C_TurnInPlaceEvaluator Parms{};

	Parms.Context = std::move(Context);
	Parms.Node = std::move(Node);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.Update Blend Weight Data
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_ItemAnimLayersBase_C::Update_Blend_Weight_Data(double DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "Update Blend Weight Data");

	Params::ABP_ItemAnimLayersBase_C_Update_Blend_Weight_Data Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.UpdateCycleAnim
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FAnimUpdateContext&        Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FAnimNodeReference&        Node                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::UpdateCycleAnim(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "UpdateCycleAnim");

	Params::ABP_ItemAnimLayersBase_C_UpdateCycleAnim Parms{};

	Parms.Context = std::move(Context);
	Parms.Node = std::move(Node);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.UpdateFallLandAnim
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FAnimUpdateContext&        Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FAnimNodeReference&        Node                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::UpdateFallLandAnim(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "UpdateFallLandAnim");

	Params::ABP_ItemAnimLayersBase_C_UpdateFallLandAnim Parms{};

	Parms.Context = std::move(Context);
	Parms.Node = std::move(Node);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.UpdateHipFireRaiseWeaponPose
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FAnimUpdateContext&        Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FAnimNodeReference&        Node                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::UpdateHipFireRaiseWeaponPose(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "UpdateHipFireRaiseWeaponPose");

	Params::ABP_ItemAnimLayersBase_C_UpdateHipFireRaiseWeaponPose Parms{};

	Parms.Context = std::move(Context);
	Parms.Node = std::move(Node);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.UpdateIdleAnim
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FAnimUpdateContext&        Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FAnimNodeReference&        Node                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::UpdateIdleAnim(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "UpdateIdleAnim");

	Params::ABP_ItemAnimLayersBase_C_UpdateIdleAnim Parms{};

	Parms.Context = std::move(Context);
	Parms.Node = std::move(Node);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.UpdateIdleState
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FAnimUpdateContext&        Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FAnimNodeReference&        Node                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::UpdateIdleState(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "UpdateIdleState");

	Params::ABP_ItemAnimLayersBase_C_UpdateIdleState Parms{};

	Parms.Context = std::move(Context);
	Parms.Node = std::move(Node);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.UpdateJumpFallData
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_ItemAnimLayersBase_C::UpdateJumpFallData(double DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "UpdateJumpFallData");

	Params::ABP_ItemAnimLayersBase_C_UpdateJumpFallData Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.UpdatePivotAnim
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FAnimUpdateContext&        Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FAnimNodeReference&        Node                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::UpdatePivotAnim(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "UpdatePivotAnim");

	Params::ABP_ItemAnimLayersBase_C_UpdatePivotAnim Parms{};

	Parms.Context = std::move(Context);
	Parms.Node = std::move(Node);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.UpdateSkelControlData
// (Public, BlueprintCallable, BlueprintEvent)

void UABP_ItemAnimLayersBase_C::UpdateSkelControlData()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "UpdateSkelControlData");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.UpdateSlideOutAnim
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FAnimUpdateContext&        Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FAnimNodeReference&        Node                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::UpdateSlideOutAnim(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "UpdateSlideOutAnim");

	Params::ABP_ItemAnimLayersBase_C_UpdateSlideOutAnim Parms{};

	Parms.Context = std::move(Context);
	Parms.Node = std::move(Node);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.UpdateStartAnim
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FAnimUpdateContext&        Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FAnimNodeReference&        Node                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::UpdateStartAnim(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "UpdateStartAnim");

	Params::ABP_ItemAnimLayersBase_C_UpdateStartAnim Parms{};

	Parms.Context = std::move(Context);
	Parms.Node = std::move(Node);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.UpdateStopAnim
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FAnimUpdateContext&        Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FAnimNodeReference&        Node                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::UpdateStopAnim(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "UpdateStopAnim");

	Params::ABP_ItemAnimLayersBase_C_UpdateStopAnim Parms{};

	Parms.Context = std::move(Context);
	Parms.Node = std::move(Node);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.UpdateTurnInPlaceRecoveryAnim
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FAnimUpdateContext&        Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FAnimNodeReference&        Node                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UABP_ItemAnimLayersBase_C::UpdateTurnInPlaceRecoveryAnim(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "UpdateTurnInPlaceRecoveryAnim");

	Params::ABP_ItemAnimLayersBase_C_UpdateTurnInPlaceRecoveryAnim Parms{};

	Parms.Context = std::move(Context);
	Parms.Node = std::move(Node);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_ItemAnimLayersBase.ABP_ItemAnimLayersBase_C.GetPredictedStopDistance
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// double                                  ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

double UABP_ItemAnimLayersBase_C::GetPredictedStopDistance() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_ItemAnimLayersBase_C", "GetPredictedStopDistance");

	Params::ABP_ItemAnimLayersBase_C_GetPredictedStopDistance Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

