#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BaseCore_Foundation4x4

#include "Basic.hpp"

#include "BP_BaseCore_Foundation4x4_classes.hpp"
#include "BP_BaseCore_Foundation4x4_parameters.hpp"


namespace SDK
{

// Function BP_BaseCore_Foundation4x4.BP_BaseCore_Foundation4x4_C.ExecuteUbergraph_BP_BaseCore_Foundation4x4
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BaseCore_Foundation4x4_C::ExecuteUbergraph_BP_BaseCore_Foundation4x4(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BaseCore_Foundation4x4_C", "ExecuteUbergraph_BP_BaseCore_Foundation4x4");

	Params::BP_BaseCore_Foundation4x4_C_ExecuteUbergraph_BP_BaseCore_Foundation4x4 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BaseCore_Foundation4x4.BP_BaseCore_Foundation4x4_C.ReceiveActorBeginOverlap
// (Event, Public, BlueprintEvent)
// Parameters:
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_BaseCore_Foundation4x4_C::ReceiveActorBeginOverlap(class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BaseCore_Foundation4x4_C", "ReceiveActorBeginOverlap");

	Params::BP_BaseCore_Foundation4x4_C_ReceiveActorBeginOverlap Parms{};

	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BaseCore_Foundation4x4.BP_BaseCore_Foundation4x4_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_BaseCore_Foundation4x4_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BaseCore_Foundation4x4_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BaseCore_Foundation4x4.BP_BaseCore_Foundation4x4_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BaseCore_Foundation4x4_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BaseCore_Foundation4x4_C", "ReceiveTick");

	Params::BP_BaseCore_Foundation4x4_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}

}

