#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: I_OnboardInstruments

#include "Basic.hpp"

#include "Chimera_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass I_OnboardInstruments.I_OnboardInstruments_C
// 0x0000 (0x0400 - 0x0400)
class UI_OnboardInstruments_C final : public UCrResourceItemBase
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("I_OnboardInstruments_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"I_OnboardInstruments_C")
	}
	static class UI_OnboardInstruments_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UI_OnboardInstruments_C>();
	}
};
DUMPER7_ASSERTS_UI_OnboardInstruments_C;

}

