#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Exporter

#include "Basic.hpp"

#include "BP_Exporter_classes.hpp"
#include "BP_Exporter_parameters.hpp"


namespace SDK
{

// Function BP_Exporter.BP_Exporter_C.Attach_meshes
// (BlueprintCallable, BlueprintEvent)

void ABP_Exporter_C::Attach_meshes()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Exporter_C", "Attach_meshes");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Exporter.BP_Exporter_C.ExecuteUbergraph_BP_Exporter
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Exporter_C::ExecuteUbergraph_BP_Exporter(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Exporter_C", "ExecuteUbergraph_BP_Exporter");

	Params::BP_Exporter_C_ExecuteUbergraph_BP_Exporter Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Exporter.BP_Exporter_C.OnBuildingStateChanged
// (Event, Public, BlueprintEvent)
// Parameters:
// ECrBuildingState                        InState                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Exporter_C::OnBuildingStateChanged(ECrBuildingState InState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Exporter_C", "OnBuildingStateChanged");

	Params::BP_Exporter_C_OnBuildingStateChanged Parms{};

	Parms.InState = InState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Exporter.BP_Exporter_C.OnCorporationChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// class FName                             NewCorporation                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Exporter_C::OnCorporationChanged(class FName NewCorporation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Exporter_C", "OnCorporationChanged");

	Params::BP_Exporter_C_OnCorporationChanged Parms{};

	Parms.NewCorporation = NewCorporation;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Exporter.BP_Exporter_C.OnItemCraftingComplete
// (Event, Public, BlueprintEvent)

void ABP_Exporter_C::OnItemCraftingComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Exporter_C", "OnItemCraftingComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Exporter.BP_Exporter_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Exporter_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Exporter_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Exporter.BP_Exporter_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Exporter_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Exporter_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

