#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_TemperatureDamageInfinite

#include "Basic.hpp"

#include "Chimera_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_TemperatureDamageInfinite.GE_TemperatureDamageInfinite_C
// 0x0000 (0x0A90 - 0x0A90)
class UGE_TemperatureDamageInfinite_C final : public UCrGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_TemperatureDamageInfinite_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_TemperatureDamageInfinite_C")
	}
	static class UGE_TemperatureDamageInfinite_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_TemperatureDamageInfinite_C>();
	}
};
DUMPER7_ASSERTS_UGE_TemperatureDamageInfinite_C;

}

