#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: I_Scafolding

#include "Basic.hpp"

#include "Chimera_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass I_Scafolding.I_Scafolding_C
// 0x0000 (0x0400 - 0x0400)
class UI_Scafolding_C final : public UCrResourceItemBase
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("I_Scafolding_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"I_Scafolding_C")
	}
	static class UI_Scafolding_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UI_Scafolding_C>();
	}
};
DUMPER7_ASSERTS_UI_Scafolding_C;

}

