#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: I_SubstanceFHS_135_493

#include "Basic.hpp"

#include "Chimera_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass I_SubstanceFHS-135-493.I_SubstanceFHS-135-493_C
// 0x0000 (0x0400 - 0x0400)
class UI_SubstanceFHS_135_493_C final : public UCrResourceItemBase
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("I_SubstanceFHS-135-493_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"I_SubstanceFHS-135-493_C")
	}
	static class UI_SubstanceFHS_135_493_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UI_SubstanceFHS_135_493_C>();
	}
};
DUMPER7_ASSERTS_UI_SubstanceFHS_135_493_C;

}

