#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_RecipeDetails

#include "Basic.hpp"

#include "WBP_RecipeDetails_classes.hpp"
#include "WBP_RecipeDetails_parameters.hpp"


namespace SDK
{

// Function WBP_RecipeDetails.WBP_RecipeDetails_C.AddOrderName
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FText&                      InText                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_RecipeDetails_C::AddOrderName(const class FText& InText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RecipeDetails_C", "AddOrderName");

	Params::WBP_RecipeDetails_C_AddOrderName Parms{};

	Parms.InText = std::move(InText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_RecipeDetails.WBP_RecipeDetails_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_RecipeDetails_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RecipeDetails_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_RecipeDetails.WBP_RecipeDetails_C.ExecuteUbergraph_WBP_RecipeDetails
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_RecipeDetails_C::ExecuteUbergraph_WBP_RecipeDetails(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RecipeDetails_C", "ExecuteUbergraph_WBP_RecipeDetails");

	Params::WBP_RecipeDetails_C_ExecuteUbergraph_WBP_RecipeDetails Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_RecipeDetails.WBP_RecipeDetails_C.SetRecipeName
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FText&                      InName                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_RecipeDetails_C::SetRecipeName(const class FText& InName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RecipeDetails_C", "SetRecipeName");

	Params::WBP_RecipeDetails_C_SetRecipeName Parms{};

	Parms.InName = std::move(InName);

	UObject::ProcessEvent(Func, &Parms);
}

}

