#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_RecipesBoxWidget

#include "Basic.hpp"

#include "WBP_RecipesBoxWidget_classes.hpp"
#include "WBP_RecipesBoxWidget_parameters.hpp"


namespace SDK
{

// Function WBP_RecipesBoxWidget.WBP_RecipesBoxWidget_C.BndEvt__WBP_CorporationRecipes_DropDownButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_RecipesBoxWidget_C::BndEvt__WBP_CorporationRecipes_DropDownButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RecipesBoxWidget_C", "BndEvt__WBP_CorporationRecipes_DropDownButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_RecipesBoxWidget.WBP_RecipesBoxWidget_C.BndEvt__WBP_CorporationRecipes_LevelButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_RecipesBoxWidget_C::BndEvt__WBP_CorporationRecipes_LevelButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RecipesBoxWidget_C", "BndEvt__WBP_CorporationRecipes_LevelButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_RecipesBoxWidget.WBP_RecipesBoxWidget_C.BndEvt__WBP_CorporationRecipes_LevelButton_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_RecipesBoxWidget_C::BndEvt__WBP_CorporationRecipes_LevelButton_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RecipesBoxWidget_C", "BndEvt__WBP_CorporationRecipes_LevelButton_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_RecipesBoxWidget.WBP_RecipesBoxWidget_C.BndEvt__WBP_CorporationRecipes_LevelButton_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_RecipesBoxWidget_C::BndEvt__WBP_CorporationRecipes_LevelButton_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RecipesBoxWidget_C", "BndEvt__WBP_CorporationRecipes_LevelButton_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_RecipesBoxWidget.WBP_RecipesBoxWidget_C.EnableLine
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bEnabled                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_RecipesBoxWidget_C::EnableLine(bool bEnabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RecipesBoxWidget_C", "EnableLine");

	Params::WBP_RecipesBoxWidget_C_EnableLine Parms{};

	Parms.bEnabled = bEnabled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_RecipesBoxWidget.WBP_RecipesBoxWidget_C.ExecuteUbergraph_WBP_RecipesBoxWidget
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_RecipesBoxWidget_C::ExecuteUbergraph_WBP_RecipesBoxWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RecipesBoxWidget_C", "ExecuteUbergraph_WBP_RecipesBoxWidget");

	Params::WBP_RecipesBoxWidget_C_ExecuteUbergraph_WBP_RecipesBoxWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_RecipesBoxWidget.WBP_RecipesBoxWidget_C.ExpandRecipes
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bExpand                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_RecipesBoxWidget_C::ExpandRecipes(bool bExpand)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RecipesBoxWidget_C", "ExpandRecipes");

	Params::WBP_RecipesBoxWidget_C_ExpandRecipes Parms{};

	Parms.bExpand = bExpand;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_RecipesBoxWidget.WBP_RecipesBoxWidget_C.SetColors
// (Event, Protected, BlueprintEvent)
// Parameters:
// const class UCrCommonUIColorsDevSettings*Settings                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_RecipesBoxWidget_C::SetColors(const class UCrCommonUIColorsDevSettings* Settings)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RecipesBoxWidget_C", "SetColors");

	Params::WBP_RecipesBoxWidget_C_SetColors Parms{};

	Parms.Settings = Settings;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_RecipesBoxWidget.WBP_RecipesBoxWidget_C.SetExpanded
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bExpand                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_RecipesBoxWidget_C::SetExpanded(bool bExpand)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RecipesBoxWidget_C", "SetExpanded");

	Params::WBP_RecipesBoxWidget_C_SetExpanded Parms{};

	Parms.bExpand = bExpand;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_RecipesBoxWidget.WBP_RecipesBoxWidget_C.SetIgnoreFocusColor
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_RecipesBoxWidget_C::SetIgnoreFocusColor(bool Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RecipesBoxWidget_C", "SetIgnoreFocusColor");

	Params::WBP_RecipesBoxWidget_C_SetIgnoreFocusColor Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_RecipesBoxWidget.WBP_RecipesBoxWidget_C.SetLevel
// (Event, Public, BlueprintEvent)
// Parameters:
// int32                                   Level                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_RecipesBoxWidget_C::SetLevel(int32 Level)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RecipesBoxWidget_C", "SetLevel");

	Params::WBP_RecipesBoxWidget_C_SetLevel Parms{};

	Parms.Level = Level;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_RecipesBoxWidget.WBP_RecipesBoxWidget_C.SetLevelButtonFocus
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bFocused                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_RecipesBoxWidget_C::SetLevelButtonFocus(bool bFocused)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RecipesBoxWidget_C", "SetLevelButtonFocus");

	Params::WBP_RecipesBoxWidget_C_SetLevelButtonFocus Parms{};

	Parms.bFocused = bFocused;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_RecipesBoxWidget.WBP_RecipesBoxWidget_C.SetLineFinished
// (Event, Public, BlueprintEvent)

void UWBP_RecipesBoxWidget_C::SetLineFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RecipesBoxWidget_C", "SetLineFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_RecipesBoxWidget.WBP_RecipesBoxWidget_C.SetLowerWidth
// (Event, Public, BlueprintEvent)

void UWBP_RecipesBoxWidget_C::SetLowerWidth()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RecipesBoxWidget_C", "SetLowerWidth");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_RecipesBoxWidget.WBP_RecipesBoxWidget_C.SetTitle
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      InText                                                 (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_RecipesBoxWidget_C::SetTitle(const class FText& InText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RecipesBoxWidget_C", "SetTitle");

	Params::WBP_RecipesBoxWidget_C_SetTitle Parms{};

	Parms.InText = std::move(InText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_RecipesBoxWidget.WBP_RecipesBoxWidget_C.SetWidgetTitle
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const class FText&                      Text                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_RecipesBoxWidget_C::SetWidgetTitle(const class FText& Text)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RecipesBoxWidget_C", "SetWidgetTitle");

	Params::WBP_RecipesBoxWidget_C_SetWidgetTitle Parms{};

	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_RecipesBoxWidget.WBP_RecipesBoxWidget_C.SetWidth
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  InSize                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_RecipesBoxWidget_C::SetWidth(double InSize)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RecipesBoxWidget_C", "SetWidth");

	Params::WBP_RecipesBoxWidget_C_SetWidth Parms{};

	Parms.InSize = InSize;

	UObject::ProcessEvent(Func, &Parms);
}

}

