#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CraftingPercentTextStyle

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CraftingPercentTextStyle.BP_CraftingPercentTextStyle_C
// 0x0000 (0x0190 - 0x0190)
class UBP_CraftingPercentTextStyle_C final : public UCommonTextStyle
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CraftingPercentTextStyle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CraftingPercentTextStyle_C")
	}
	static class UBP_CraftingPercentTextStyle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_CraftingPercentTextStyle_C>();
	}
};
DUMPER7_ASSERTS_UBP_CraftingPercentTextStyle_C;

}

