#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_decal_blood_gradient_a_outdoor

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_decal_blood_gradient_a_outdoor.BP_decal_blood_gradient_a_outdoor_C
// 0x0018 (0x02C0 - 0x02A8)
class ABP_decal_blood_gradient_a_outdoor_C final : public AActor
{
public:
	class UDecalComponent*                        Decal;                                             // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UArrowComponent*                        Arrow;                                             // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_decal_blood_gradient_a_outdoor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_decal_blood_gradient_a_outdoor_C")
	}
	static class ABP_decal_blood_gradient_a_outdoor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_decal_blood_gradient_a_outdoor_C>();
	}
};
DUMPER7_ASSERTS_ABP_decal_blood_gradient_a_outdoor_C;

}

