#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Gatherable_NootkaLupine_Fruit

#include "Basic.hpp"

#include "BP_GatherableBaseActor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Gatherable_NootkaLupine_Fruit.BP_Gatherable_NootkaLupine_Fruit_C
// 0x0000 (0x0380 - 0x0380)
class ABP_Gatherable_NootkaLupine_Fruit_C final : public ABP_GatherableBaseActor_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Gatherable_NootkaLupine_Fruit_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Gatherable_NootkaLupine_Fruit_C")
	}
	static class ABP_Gatherable_NootkaLupine_Fruit_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Gatherable_NootkaLupine_Fruit_C>();
	}
};
DUMPER7_ASSERTS_ABP_Gatherable_NootkaLupine_Fruit_C;

}

