#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PersonalStorageBig

#include "Basic.hpp"

#include "BP_PersonalStorageBig_classes.hpp"
#include "BP_PersonalStorageBig_parameters.hpp"


namespace SDK
{

// Function BP_PersonalStorageBig.BP_PersonalStorageBig_C.ExecuteUbergraph_BP_PersonalStorageBig
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PersonalStorageBig_C::ExecuteUbergraph_BP_PersonalStorageBig(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PersonalStorageBig_C", "ExecuteUbergraph_BP_PersonalStorageBig");

	Params::BP_PersonalStorageBig_C_ExecuteUbergraph_BP_PersonalStorageBig Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PersonalStorageBig.BP_PersonalStorageBig_C.OnNameChanged
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    NewName                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void ABP_PersonalStorageBig_C::OnNameChanged(const class FString& NewName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PersonalStorageBig_C", "OnNameChanged");

	Params::BP_PersonalStorageBig_C_OnNameChanged Parms{};

	Parms.NewName = std::move(NewName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PersonalStorageBig.BP_PersonalStorageBig_C.OnUIOpened
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bOpened                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PersonalStorageBig_C::OnUIOpened(bool bOpened)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PersonalStorageBig_C", "OnUIOpened");

	Params::BP_PersonalStorageBig_C_OnUIOpened Parms{};

	Parms.bOpened = bOpened;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PersonalStorageBig.BP_PersonalStorageBig_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_PersonalStorageBig_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PersonalStorageBig_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PersonalStorageBig.BP_PersonalStorageBig_C.UpdateDisplayedPersonalStorageName
// (BlueprintCallable, BlueprintEvent)

void ABP_PersonalStorageBig_C::UpdateDisplayedPersonalStorageName()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PersonalStorageBig_C", "UpdateDisplayedPersonalStorageName");

	UObject::ProcessEvent(Func, nullptr);
}

}

