#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Sulphur_Logic_Small

#include "Basic.hpp"

#include "BP_Sulphur_Logic_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Sulphur_Logic_Small.BP_Sulphur_Logic_Small_C
// 0x0000 (0x02F0 - 0x02F0)
class ABP_Sulphur_Logic_Small_C final : public ABP_Sulphur_Logic_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Sulphur_Logic_Small_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Sulphur_Logic_Small_C")
	}
	static class ABP_Sulphur_Logic_Small_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Sulphur_Logic_Small_C>();
	}
};
DUMPER7_ASSERTS_ABP_Sulphur_Logic_Small_C;

}

