#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_RemovingTemperatureFromBuilding

#include "Basic.hpp"

#include "GA_RemovingTemperatureFromBuilding_classes.hpp"
#include "GA_RemovingTemperatureFromBuilding_parameters.hpp"


namespace SDK
{

// Function GA_RemovingTemperatureFromBuilding.GA_RemovingTemperatureFromBuilding_C.ExecuteUbergraph_GA_RemovingTemperatureFromBuilding
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_RemovingTemperatureFromBuilding_C::ExecuteUbergraph_GA_RemovingTemperatureFromBuilding(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_RemovingTemperatureFromBuilding_C", "ExecuteUbergraph_GA_RemovingTemperatureFromBuilding");

	Params::GA_RemovingTemperatureFromBuilding_C_ExecuteUbergraph_GA_RemovingTemperatureFromBuilding Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_RemovingTemperatureFromBuilding.GA_RemovingTemperatureFromBuilding_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_RemovingTemperatureFromBuilding_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_RemovingTemperatureFromBuilding_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_RemovingTemperatureFromBuilding.GA_RemovingTemperatureFromBuilding_C.OnCancelled_DE1FC1395847D031455AF3B86AE5B04D
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_RemovingTemperatureFromBuilding_C::OnCancelled_DE1FC1395847D031455AF3B86AE5B04D(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_RemovingTemperatureFromBuilding_C", "OnCancelled_DE1FC1395847D031455AF3B86AE5B04D");

	Params::GA_RemovingTemperatureFromBuilding_C_OnCancelled_DE1FC1395847D031455AF3B86AE5B04D Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_RemovingTemperatureFromBuilding.GA_RemovingTemperatureFromBuilding_C.OnFppMontageBlendOut_DE1FC1395847D031455AF3B86AE5B04D
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_RemovingTemperatureFromBuilding_C::OnFppMontageBlendOut_DE1FC1395847D031455AF3B86AE5B04D(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_RemovingTemperatureFromBuilding_C", "OnFppMontageBlendOut_DE1FC1395847D031455AF3B86AE5B04D");

	Params::GA_RemovingTemperatureFromBuilding_C_OnFppMontageBlendOut_DE1FC1395847D031455AF3B86AE5B04D Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_RemovingTemperatureFromBuilding.GA_RemovingTemperatureFromBuilding_C.OnFppMontageEnded_DE1FC1395847D031455AF3B86AE5B04D
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_RemovingTemperatureFromBuilding_C::OnFppMontageEnded_DE1FC1395847D031455AF3B86AE5B04D(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_RemovingTemperatureFromBuilding_C", "OnFppMontageEnded_DE1FC1395847D031455AF3B86AE5B04D");

	Params::GA_RemovingTemperatureFromBuilding_C_OnFppMontageEnded_DE1FC1395847D031455AF3B86AE5B04D Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_RemovingTemperatureFromBuilding.GA_RemovingTemperatureFromBuilding_C.OnFppMontageNotifyBegin_DE1FC1395847D031455AF3B86AE5B04D
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_RemovingTemperatureFromBuilding_C::OnFppMontageNotifyBegin_DE1FC1395847D031455AF3B86AE5B04D(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_RemovingTemperatureFromBuilding_C", "OnFppMontageNotifyBegin_DE1FC1395847D031455AF3B86AE5B04D");

	Params::GA_RemovingTemperatureFromBuilding_C_OnFppMontageNotifyBegin_DE1FC1395847D031455AF3B86AE5B04D Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_RemovingTemperatureFromBuilding.GA_RemovingTemperatureFromBuilding_C.OnFppMontageNotifyEnd_DE1FC1395847D031455AF3B86AE5B04D
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_RemovingTemperatureFromBuilding_C::OnFppMontageNotifyEnd_DE1FC1395847D031455AF3B86AE5B04D(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_RemovingTemperatureFromBuilding_C", "OnFppMontageNotifyEnd_DE1FC1395847D031455AF3B86AE5B04D");

	Params::GA_RemovingTemperatureFromBuilding_C_OnFppMontageNotifyEnd_DE1FC1395847D031455AF3B86AE5B04D Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_RemovingTemperatureFromBuilding.GA_RemovingTemperatureFromBuilding_C.OnInterrupted_DE1FC1395847D031455AF3B86AE5B04D
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_RemovingTemperatureFromBuilding_C::OnInterrupted_DE1FC1395847D031455AF3B86AE5B04D(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_RemovingTemperatureFromBuilding_C", "OnInterrupted_DE1FC1395847D031455AF3B86AE5B04D");

	Params::GA_RemovingTemperatureFromBuilding_C_OnInterrupted_DE1FC1395847D031455AF3B86AE5B04D Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_RemovingTemperatureFromBuilding.GA_RemovingTemperatureFromBuilding_C.OnNotLocallyControlledTppMontageBlendOut_DE1FC1395847D031455AF3B86AE5B04D
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_RemovingTemperatureFromBuilding_C::OnNotLocallyControlledTppMontageBlendOut_DE1FC1395847D031455AF3B86AE5B04D(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_RemovingTemperatureFromBuilding_C", "OnNotLocallyControlledTppMontageBlendOut_DE1FC1395847D031455AF3B86AE5B04D");

	Params::GA_RemovingTemperatureFromBuilding_C_OnNotLocallyControlledTppMontageBlendOut_DE1FC1395847D031455AF3B86AE5B04D Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}

}

