#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_CamEffect_Toxicity

#include "Basic.hpp"

#include "GE_CamEffect_Toxicity_classes.hpp"
#include "GE_CamEffect_Toxicity_parameters.hpp"


namespace SDK
{

// Function GE_CamEffect_Toxicity.GE_CamEffect_Toxicity_C.ExecuteUbergraph_GE_CamEffect_Toxicity
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGE_CamEffect_Toxicity_C::ExecuteUbergraph_GE_CamEffect_Toxicity(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GE_CamEffect_Toxicity_C", "ExecuteUbergraph_GE_CamEffect_Toxicity");

	Params::GE_CamEffect_Toxicity_C_ExecuteUbergraph_GE_CamEffect_Toxicity Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GE_CamEffect_Toxicity.GE_CamEffect_Toxicity_C.OnAttributeChanged_A4A28E1642D1C6B685D41AB7D42333B7
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayAttribute&        Attribute                                              (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
// float                                   NewValue                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   OldValue                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGE_CamEffect_Toxicity_C::OnAttributeChanged_A4A28E1642D1C6B685D41AB7D42333B7(const struct FGameplayAttribute& Attribute, float NewValue, float OldValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GE_CamEffect_Toxicity_C", "OnAttributeChanged_A4A28E1642D1C6B685D41AB7D42333B7");

	Params::GE_CamEffect_Toxicity_C_OnAttributeChanged_A4A28E1642D1C6B685D41AB7D42333B7 Parms{};

	Parms.Attribute = std::move(Attribute);
	Parms.NewValue = NewValue;
	Parms.OldValue = OldValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GE_CamEffect_Toxicity.GE_CamEffect_Toxicity_C.OnInitialized
// (Event, Public, BlueprintEvent)
// Parameters:
// class UAbilitySystemComponent*          AbilitySystemComponent                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// TSubclassOf<class UGameplayEffect>      GameplayEffect                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
// class USceneComponent*                  OwnerRootComponent                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UGE_CamEffect_Toxicity_C::OnInitialized(class UAbilitySystemComponent* AbilitySystemComponent, TSubclassOf<class UGameplayEffect> GameplayEffect, class USceneComponent* OwnerRootComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GE_CamEffect_Toxicity_C", "OnInitialized");

	Params::GE_CamEffect_Toxicity_C_OnInitialized Parms{};

	Parms.AbilitySystemComponent = AbilitySystemComponent;
	Parms.GameplayEffect = GameplayEffect;
	Parms.OwnerRootComponent = OwnerRootComponent;

	UObject::ProcessEvent(Func, &Parms);
}

}

