#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_CamEffectHealing

#include "Basic.hpp"

#include "Chimera_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_CamEffectHealing.GE_CamEffectHealing_C
// 0x0008 (0x0AB0 - 0x0AA8)
class UGE_CamEffectHealing_C final : public UCrCameraGameplayEffect
{
public:
	class UClass*                                 GE_Healing;                                        // 0x0AA8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_CamEffectHealing_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_CamEffectHealing_C")
	}
	static class UGE_CamEffectHealing_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_CamEffectHealing_C>();
	}
};
DUMPER7_ASSERTS_UGE_CamEffectHealing_C;

}

