#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: I_PlasticDust

#include "Basic.hpp"

#include "Chimera_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass I_PlasticDust.I_PlasticDust_C
// 0x0000 (0x0400 - 0x0400)
class UI_PlasticDust_C final : public UCrResourceItemBase
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("I_PlasticDust_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"I_PlasticDust_C")
	}
	static class UI_PlasticDust_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UI_PlasticDust_C>();
	}
};
DUMPER7_ASSERTS_UI_PlasticDust_C;

}

