#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: I_PowerCell

#include "Basic.hpp"

#include "Chimera_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass I_PowerCell.I_PowerCell_C
// 0x0000 (0x0400 - 0x0400)
class UI_PowerCell_C final : public UCrResourceItemBase
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("I_PowerCell_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"I_PowerCell_C")
	}
	static class UI_PowerCell_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UI_PowerCell_C>();
	}
};
DUMPER7_ASSERTS_UI_PowerCell_C;

}

