#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Map_MainMenu

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Map_MainMenu.Map_MainMenu_C
// 0x0010 (0x02C0 - 0x02B0)
class AMap_MainMenu_C final : public ALevelScriptActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UAudioComponent*                        MenuMusic;                                         // 0x02B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)

public:
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);
	void ReceiveDestroyed();
	void ReceiveBeginPlay();
	void getLevelName();
	void ExecuteUbergraph_Map_MainMenu(int32 EntryPoint);
	void droneFPV();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Map_MainMenu_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Map_MainMenu_C")
	}
	static class AMap_MainMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMap_MainMenu_C>();
	}
};
DUMPER7_ASSERTS_AMap_MainMenu_C;

}

