#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_EncyclopediaAudiologInfoMenu

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ChimeraUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_EncyclopediaAudiologInfoMenu.WBP_EncyclopediaAudiologInfoMenu_C
// 0x0020 (0x0820 - 0x0800)
class UWBP_EncyclopediaAudiologInfoMenu_C final : public UCrUW_EncyclopediaAudiologInfoMenu
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0800(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Image_312;                                         // 0x0808(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_HeaderLineBuildingInfo_C*          EntryName;                                         // 0x0810(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScrollBox*                             ChaptersScrollbox;                                 // 0x0818(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_EncyclopediaAudiologInfoMenu(int32 EntryPoint);
	void SetEntryTitleBP(const class FText& Title);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_EncyclopediaAudiologInfoMenu_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_EncyclopediaAudiologInfoMenu_C")
	}
	static class UWBP_EncyclopediaAudiologInfoMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_EncyclopediaAudiologInfoMenu_C>();
	}
};
DUMPER7_ASSERTS_UWBP_EncyclopediaAudiologInfoMenu_C;

}

