#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_InventoryGemSlot

#include "Basic.hpp"

#include "WBP_InventoryGemSlot_classes.hpp"
#include "WBP_InventoryGemSlot_parameters.hpp"


namespace SDK
{

// Function WBP_InventoryGemSlot.WBP_InventoryGemSlot_C.ConvertToGrayScale
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FColor&                    InColor                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UWBP_InventoryGemSlot_C::ConvertToGrayScale(const struct FColor& InColor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InventoryGemSlot_C", "ConvertToGrayScale");

	Params::WBP_InventoryGemSlot_C_ConvertToGrayScale Parms{};

	Parms.InColor = std::move(InColor);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_InventoryGemSlot.WBP_InventoryGemSlot_C.ExecuteUbergraph_WBP_InventoryGemSlot
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_InventoryGemSlot_C::ExecuteUbergraph_WBP_InventoryGemSlot(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InventoryGemSlot_C", "ExecuteUbergraph_WBP_InventoryGemSlot");

	Params::WBP_InventoryGemSlot_C_ExecuteUbergraph_WBP_InventoryGemSlot Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InventoryGemSlot.WBP_InventoryGemSlot_C.HideFullStackIcon
// (BlueprintCallable, BlueprintEvent)

void UWBP_InventoryGemSlot_C::HideFullStackIcon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InventoryGemSlot_C", "HideFullStackIcon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_InventoryGemSlot.WBP_InventoryGemSlot_C.SetBackgroundColor
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FColor&                    InColor                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_InventoryGemSlot_C::SetBackgroundColor(const struct FColor& InColor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InventoryGemSlot_C", "SetBackgroundColor");

	Params::WBP_InventoryGemSlot_C_SetBackgroundColor Parms{};

	Parms.InColor = std::move(InColor);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InventoryGemSlot.WBP_InventoryGemSlot_C.SetDefaultBrush
// (Event, Public, BlueprintEvent)

void UWBP_InventoryGemSlot_C::SetDefaultBrush()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InventoryGemSlot_C", "SetDefaultBrush");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_InventoryGemSlot.WBP_InventoryGemSlot_C.SetFullStackColor
// (Event, Protected, BlueprintEvent)
// Parameters:
// const struct FColor&                    InColor                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_InventoryGemSlot_C::SetFullStackColor(const struct FColor& InColor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InventoryGemSlot_C", "SetFullStackColor");

	Params::WBP_InventoryGemSlot_C_SetFullStackColor Parms{};

	Parms.InColor = std::move(InColor);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InventoryGemSlot.WBP_InventoryGemSlot_C.SetFullStackHighlight
// (Event, Public, BlueprintEvent)

void UWBP_InventoryGemSlot_C::SetFullStackHighlight()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InventoryGemSlot_C", "SetFullStackHighlight");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_InventoryGemSlot.WBP_InventoryGemSlot_C.SetGrayedNames
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bGray                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_InventoryGemSlot_C::SetGrayedNames(bool bGray)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InventoryGemSlot_C", "SetGrayedNames");

	Params::WBP_InventoryGemSlot_C_SetGrayedNames Parms{};

	Parms.bGray = bGray;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InventoryGemSlot.WBP_InventoryGemSlot_C.SetGrayScaleTex
// (Event, Protected, BlueprintEvent)
// Parameters:
// const struct FSlateBrush&               InBrush                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_InventoryGemSlot_C::SetGrayScaleTex(const struct FSlateBrush& InBrush)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InventoryGemSlot_C", "SetGrayScaleTex");

	Params::WBP_InventoryGemSlot_C_SetGrayScaleTex Parms{};

	Parms.InBrush = std::move(InBrush);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InventoryGemSlot.WBP_InventoryGemSlot_C.SetHighlightColor
// (Event, Protected, BlueprintEvent)
// Parameters:
// const struct FLinearColor&              InColor                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_InventoryGemSlot_C::SetHighlightColor(const struct FLinearColor& InColor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InventoryGemSlot_C", "SetHighlightColor");

	Params::WBP_InventoryGemSlot_C_SetHighlightColor Parms{};

	Parms.InColor = std::move(InColor);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InventoryGemSlot.WBP_InventoryGemSlot_C.SetSlotSize
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector2D&                 InSize                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_InventoryGemSlot_C::SetSlotSize(const struct FVector2D& InSize)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InventoryGemSlot_C", "SetSlotSize");

	Params::WBP_InventoryGemSlot_C_SetSlotSize Parms{};

	Parms.InSize = std::move(InSize);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InventoryGemSlot.WBP_InventoryGemSlot_C.ShowItemNameInIcon
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const class FText&                      InText                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// bool                                    Show                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_InventoryGemSlot_C::ShowItemNameInIcon(const class FText& InText, bool Show)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InventoryGemSlot_C", "ShowItemNameInIcon");

	Params::WBP_InventoryGemSlot_C_ShowItemNameInIcon Parms{};

	Parms.InText = std::move(InText);
	Parms.Show = Show;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InventoryGemSlot.WBP_InventoryGemSlot_C.UpdateVisuals
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bInLocked                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Level_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_InventoryGemSlot_C::UpdateVisuals(bool bInLocked, int32 Level_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InventoryGemSlot_C", "UpdateVisuals");

	Params::WBP_InventoryGemSlot_C_UpdateVisuals Parms{};

	Parms.bInLocked = bInLocked;
	Parms.Level_0 = Level_0;

	UObject::ProcessEvent(Func, &Parms);
}

}

