#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Inventory

#include "Basic.hpp"

#include "ChimeraUI_structs.hpp"
#include "ChimeraUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Inventory.WBP_Inventory_C
// 0x0000 (0x0628 - 0x0628)
class UWBP_Inventory_C final : public UCrUW_Inventory
{
public:
	void MakeButtonBrush(ETabIcon Icon, struct FSlateBrush* Brush);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Inventory_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Inventory_C")
	}
	static class UWBP_Inventory_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Inventory_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Inventory_C;

}

