#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CraftingRecipeTime

#include "Basic.hpp"

#include "ChimeraUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_CraftingRecipeTime.WBP_CraftingRecipeTime_C
// 0x0018 (0x0608 - 0x05F0)
class UWBP_CraftingRecipeTime_C final : public UCrUW_CraftingRecipeTime
{
public:
	class UImage*                                 Image_238;                                         // 0x05F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_156;                                         // 0x05F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_93;                                          // 0x0600(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_CraftingRecipeTime_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_CraftingRecipeTime_C")
	}
	static class UWBP_CraftingRecipeTime_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CraftingRecipeTime_C>();
	}
};
DUMPER7_ASSERTS_UWBP_CraftingRecipeTime_C;

}

