#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPW_ResolutionMenu

#include "Basic.hpp"

#include "BPW_ResolutionMenu_classes.hpp"
#include "BPW_ResolutionMenu_parameters.hpp"


namespace SDK
{

// Function BPW_ResolutionMenu.BPW_ResolutionMenu_C.SelectionChanged_Event_0
// (BlueprintCallable, BlueprintEvent)

void UBPW_ResolutionMenu_C::SelectionChanged_Event_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_ResolutionMenu_C", "SelectionChanged_Event_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPW_ResolutionMenu.BPW_ResolutionMenu_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPW_ResolutionMenu_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_ResolutionMenu_C", "PreConstruct");

	Params::BPW_ResolutionMenu_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPW_ResolutionMenu.BPW_ResolutionMenu_C.InitResolution
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UGameUserSettings*                GameUserSettings                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBPW_ResolutionMenu_C::InitResolution(class UGameUserSettings* GameUserSettings)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_ResolutionMenu_C", "InitResolution");

	Params::BPW_ResolutionMenu_C_InitResolution Parms{};

	Parms.GameUserSettings = GameUserSettings;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPW_ResolutionMenu.BPW_ResolutionMenu_C.ExecuteUbergraph_BPW_ResolutionMenu
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPW_ResolutionMenu_C::ExecuteUbergraph_BPW_ResolutionMenu(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_ResolutionMenu_C", "ExecuteUbergraph_BPW_ResolutionMenu");

	Params::BPW_ResolutionMenu_C_ExecuteUbergraph_BPW_ResolutionMenu Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPW_ResolutionMenu.BPW_ResolutionMenu_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBPW_ResolutionMenu_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_ResolutionMenu_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

