#!/usr/bin/env python3
"""One-off generator: reads the raw GObjects/UFunction dump produced by
Hooks::GObjectWalk::ExportKnownClassesAndFunctions and writes a curated
known_gobjects.generated.h with class-name constants for all Cr/Au-prefixed
game classes (bucketed into rough categories) plus function-name constants
for a short list of explicitly requested engine classes.

Not part of the build -- run manually, inspect the output, then commit the
generated header. Re-run whenever the SDK updates and new classes/functions
are suspected.
"""
import re
import sys
from collections import defaultdict, OrderedDict

DUMP_PATH = sys.argv[1] if len(sys.argv) > 1 else "known_gobjects_dump.txt"
OUT_PATH = sys.argv[2] if len(sys.argv) > 2 else "known_gobjects.generated.h"

# Engine classes the user explicitly asked for -- emit full function lists.
ENGINE_CLASSES = [
    "Actor", "Pawn", "Controller", "PlayerController", "World", "HUD",
    "Viewport", "GameViewportClient", "CrGameViewportClient", "CommonGameViewportClient",
    "KismetSystemLibrary",
]

# Bucketing heuristics for Cr/Au-prefixed game classes (class-name only, no
# functions -- there are thousands of these, function lists would be noise).
CATEGORY_RULES = OrderedDict([
    ("UI",         [r"^CrUW_", r"Widget$", r"^CrHUD"]),
    ("AI",         [r"AI", r"Enemy", r"Spawner", r"Spawn"]),
    ("Building",   [r"Build", r"Construct", r"Deconstruct"]),
    ("Crafting",   [r"Craft", r"Recipe", r"Extractor", r"Refinery", r"Assembler", r"Printer"]),
    ("Inventory",  [r"Inventory", r"Item", r"Storage"]),
    ("Player",     [r"Player", r"Character", r"Ability", r"Attribute"]),
    ("World",      [r"World", r"Biome", r"Terrain", r"Zone"]),
])


def sanitize(name: str) -> str:
    # Make a valid C++ identifier (handles names like BP_Foo_C, names with
    # digits at start, etc.)
    out = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if out and out[0].isdigit():
        out = "_" + out
    return out


def categorize(class_name: str) -> str:
    for category, patterns in CATEGORY_RULES.items():
        for pat in patterns:
            if re.search(pat, class_name):
                return category
    return "Misc"


def main():
    classes = OrderedDict()  # class_name -> list[func_name]
    with open(DUMP_PATH, "r", encoding="utf-8", errors="replace") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line:
                continue
            if "." in line:
                cls, func = line.split(".", 1)
            else:
                cls, func = line, None
            classes.setdefault(cls, [])
            if func:
                classes[cls].append(func)

    engine_out = OrderedDict()
    cr_au_buckets = defaultdict(list)  # category -> [class_name]

    for cls, funcs in classes.items():
        if cls in ENGINE_CLASSES:
            engine_out[cls] = funcs
        elif cls.startswith("Cr") or cls.startswith("Au"):
            cr_au_buckets[categorize(cls)].append(cls)

    with open(OUT_PATH, "w", encoding="ascii", errors="replace") as out:
        out.write("#pragma once\n\n")
        out.write("// Auto-generated by plugins/gen_known_gobjects.py from a raw GObjects dump\n")
        out.write("// (Hooks::GObjectWalk::ExportKnownClassesAndFunctions). DO NOT hand-edit --\n")
        out.write("// re-run the generator against a fresh dump and re-curate instead.\n")
        out.write("//\n")
        out.write("// Provides compile-time string constants for known engine/game class and\n")
        out.write("// UFunction names so plugin code gets IDE autocomplete, e.g.:\n")
        out.write("//   hooks->ObjectWalker->FindObjectsByClassName(KnownClasses::Building::CrCrafter, ...)\n")
        out.write("//   hooks->ObjectWalker->InvokeUFunctionByName(obj, KnownClasses::Engine::Actor,\n")
        out.write("//       KnownFunctions::Actor::SetActorHiddenInGame, &params)\n\n")

        out.write("namespace KnownClasses\n{\n")

        out.write("\tnamespace Engine\n\t{\n")
        for cls in engine_out:
            out.write(f'\t\tconstexpr const char* {sanitize(cls)} = "{cls}";\n')
        out.write("\t}\n\n")

        for category, cls_list in cr_au_buckets.items():
            out.write(f"\tnamespace {category}\n\t{{\n")
            for cls in sorted(set(cls_list)):
                out.write(f'\t\tconstexpr const char* {sanitize(cls)} = "{cls}";\n')
            out.write("\t}\n\n")

        out.write("}\n\n")

        out.write("namespace KnownFunctions\n{\n")
        for cls, funcs in engine_out.items():
            if not funcs:
                continue
            out.write(f"\tnamespace {sanitize(cls)}\n\t{{\n")
            for fn in sorted(set(funcs)):
                out.write(f'\t\tconstexpr const char* {sanitize(fn)} = "{fn}";\n')
            out.write("\t}\n\n")
        out.write("}\n")

    total_classes = len(engine_out) + sum(len(v) for v in cr_au_buckets.values())
    print(f"Wrote {OUT_PATH}: {len(engine_out)} engine classes (with functions), "
          f"{sum(len(v) for v in cr_au_buckets.values())} Cr/Au classes (name-only) "
          f"across categories: {', '.join(f'{k}={len(v)}' for k, v in cr_au_buckets.items())}")


if __name__ == "__main__":
    main()
