"""Generate the Material Icons reference for ModLoader plugin authors.

Reads the embedded icon font's cmap directly, renders contact sheets with the
codepoint baked under each glyph, and writes a markdown reference.

The font's `post` table is version 3.0, which by spec carries no glyph names --
so the sheets are the index. There is nothing else in the file to look them up by.
"""

import os
import struct

ML = r"C:\Users\markp\Documents\GitHub\StarRupture-ModLoader"
FONT = os.path.join(ML, r"StarRupture-ImGui\custom_fonts\MaterialIcons-Regular.ttf")
LABEL_FONT = os.path.join(ML, r"StarRupture-ImGui\imgui\misc\fonts\Cousine-Regular.ttf")

OUT_MD = os.path.join(ML, "MaterialIcons.md")
OUT_DIR = os.path.join(ML, "MaterialIcons")

COLS, ROWS = 16, 16
CELL_W, CELL_H = 72, 64
GLYPH_PX, LABEL_PX = 34, 11
BG = (30, 33, 38)
BG_ALT = (36, 40, 46)
FG = (240, 242, 245)
LABEL = (150, 164, 176)


def pua_codepoints(path):
    d = open(path, 'rb').read()
    n = struct.unpack('>H', d[4:6])[0]
    tabs = {}
    for i in range(n):
        off = 12 + 16 * i
        tag = d[off:off + 4].decode('latin1')
        o, l = struct.unpack('>II', d[off + 8:off + 16])
        tabs[tag] = (o, l)

    co, _ = tabs['cmap']
    nt = struct.unpack('>H', d[co + 2:co + 4])[0]
    cps = set()
    for i in range(nt):
        pid, eid, so = struct.unpack('>HHI', d[co + 4 + 8 * i:co + 12 + 8 * i])
        so += co
        if struct.unpack('>H', d[so:so + 2])[0] == 12:
            ng = struct.unpack('>I', d[so + 12:so + 16])[0]
            for j in range(ng):
                s, e, g = struct.unpack('>III', d[so + 16 + 12 * j:so + 28 + 12 * j])
                cps.update(range(s, e + 1))
    return sorted(c for c in cps if 0xE000 <= c <= 0xF8FF)


def escape(cp):
    return ''.join('\\x%02X' % b for b in chr(cp).encode('utf-8'))


def main():
    from PIL import Image, ImageDraw, ImageFont

    cps = pua_codepoints(FONT)
    os.makedirs(OUT_DIR, exist_ok=True)

    glyph_font = ImageFont.truetype(FONT, GLYPH_PX)
    label_font = ImageFont.truetype(LABEL_FONT, LABEL_PX)

    per_sheet = COLS * ROWS
    sheets = []

    for start in range(0, len(cps), per_sheet):
        chunk = cps[start:start + per_sheet]
        rows = (len(chunk) + COLS - 1) // COLS
        img = Image.new('RGB', (COLS * CELL_W, rows * CELL_H), BG)
        dr = ImageDraw.Draw(img)

        for i, cp in enumerate(chunk):
            cx, cy = (i % COLS) * CELL_W, (i // COLS) * CELL_H
            if ((i % COLS) + (i // COLS)) % 2:
                dr.rectangle([cx, cy, cx + CELL_W - 1, cy + CELL_H - 1], fill=BG_ALT)

            ch = chr(cp)
            box = dr.textbbox((0, 0), ch, font=glyph_font)
            dr.text((cx + (CELL_W - (box[2] - box[0])) / 2 - box[0],
                     cy + 6 - box[1]), ch, font=glyph_font, fill=FG)

            lab = '%04X' % cp
            lbox = dr.textbbox((0, 0), lab, font=label_font)
            dr.text((cx + (CELL_W - (lbox[2] - lbox[0])) / 2 - lbox[0],
                     cy + CELL_H - 16), lab, font=label_font, fill=LABEL)

        name = 'sheet-%02d.png' % (len(sheets) + 1)
        img.save(os.path.join(OUT_DIR, name))
        sheets.append((name, chunk[0], chunk[-1], len(chunk)))
        print('wrote %s  (%d icons, U+%04X..U+%04X)' % (name, len(chunk), chunk[0], chunk[-1]))

    with open(OUT_MD, 'w', encoding='utf-8') as f:
        f.write(HEADER.format(count=len(cps), sheets=len(sheets)))

        f.write('\n## Sheets\n\n')
        f.write('The hex under each glyph is its codepoint. Find the icon you want, '
                'read the code, then look the escape up in the table at the bottom '
                '(or derive it -- see above).\n')
        for name, lo, hi, cnt in sheets:
            f.write('\n### U+%04X - U+%04X  (%d icons)\n\n' % (lo, hi, cnt))
            f.write('![U+%04X to U+%04X](MaterialIcons/%s)\n' % (lo, hi, name))

        f.write('\n## Full lookup\n\n')
        f.write('Every glyph the bundled font actually maps, with the C string '
                'escape for each. `%d` entries.\n\n```\n' % len(cps))
        for cp in cps:
            f.write('U+%04X  "%s"\n' % (cp, escape(cp)))
        f.write('```\n')

    print('wrote %s  (%d icons)' % (OUT_MD, len(cps)))


HEADER = '''# Material Icons reference

The ModLoader embeds **MaterialIcons-Regular.ttf** as an RCDATA resource
(`IDR_ICON_FONT`, see `StarRupture-ImGui/StarRupture-ImGui.rc`) and merges it into
the ImGui font atlas in `imgui_backend.cpp`'s `RebuildFontAtlas()`. This file lists
every glyph in it: **{count} icons** across {sheets} sheets.

See also [ImGui_Dev.md](ImGui_Dev.md) for the wider ImGui integration.

> Generated by [`tools/gen_material_icons.py`](tools/gen_material_icons.py) (needs Pillow) straight
> from the font's `cmap`. Re-run it if the bundled font is ever replaced -- the counts and sheets
> below are specific to the file currently in the repo.

## Plugins need no setup to use these

ImGui 1.92 reworked fonts to load glyphs **on demand**. The ModLoader initialises
the DX12 backend through `ImGui_ImplDX12_Init(ImGui_ImplDX12_InitInfo*)`, which sets
`ImGuiBackendFlags_RendererHasTextures` -- so `ImFontAtlasBuildLegacyPreloadAllGlyphRanges`
never runs, and `ImFontConfig::GlyphRanges` is only a *preload* hint rather than a
restriction. The short list in `s_iconRange` is what gets baked at startup; anything
else is baked the first time it is drawn.

The practical consequence: **any codepoint below is usable from any plugin right now.**
No interface call, no atlas rebuild, no ModLoader change. Just emit the UTF-8 bytes.

```cpp
// Play / pause on a transport button. The ##id suffix matters -- ImGui derives a
// widget's identity from its label, so two buttons showing the same glyph would
// otherwise be the same widget.
const char* label = playing ? "\\xEE\\x80\\xB4##play"    // pause
                            : "\\xEE\\x80\\xB7##play";   // play_arrow
if (ui->ButtonSized(label, 34.0f, height))
    playing = !playing;
```

## Why there are no names here

The font's `post` table is version 3.0, which by specification stores no glyph
names -- so the file itself cannot tell you that `U+E037` is `play_arrow`. Upstream
publishes a `MaterialIcons-Regular.codepoints` text file with the name/codepoint
pairs if you want them; nothing in this repository carries them. Hence the sheets:
you identify an icon by looking at it.

## Codepoint to C escape

Every one of these sits in the Basic Multilingual Plane, so UTF-8 is always three
bytes: `1110xxxx 10xxxxxx 10xxxxxx`, filled from the low 16 bits of the codepoint.

    U+E037  ->  1110 | 0000 0011 0111
            ->  split 4/6/6:  1110 | 000000 | 110111
            ->  0xEE, 0x80, 0xB7        ->  "\\xEE\\x80\\xB7"

Note `ImWchar` is 16-bit here (`IMGUI_USE_WCHAR32` is commented out in
`imconfig.h`), which is fine for this private-use block but means real emoji
(U+1F300 and up) cannot be expressed at all -- and would need a colour-capable
rasteriser regardless.
'''


if __name__ == '__main__':
    main()
