name: 'Repo Notifications'

on:
  issues:
    types: [opened, reopened, closed]
  pull_request:
    types: [opened, reopened, closed]

jobs:
  notify-issue:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - name: Send issue notification
        uses: stegzilla/discord-notify@v2
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: Issue Update
          message: "**${{ github.event.issue.title }}**\n**Creator:** ${{ github.event.issue.user.login }}\n${{ github.event.issue.html_url }}"
          username: GitHub Issue Notifier

  notify-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Send PR notification
        uses: stegzilla/discord-notify@v2
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: PR Update
          message: "**${{ github.event.pull_request.title }}**\n**Creator:** ${{ github.event.pull_request.user.login }}\n${{ github.event.pull_request.html_url }}"
          username: GitHub PR Notifier