#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ALI_ItemAnimLayers

#include "Basic.hpp"

#include "ALI_ItemAnimLayers_classes.hpp"
#include "ALI_ItemAnimLayers_parameters.hpp"


namespace SDK
{

// Function ALI_ItemAnimLayers.ALI_ItemAnimLayers_C.FullBody_Aiming
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FPoseLink&                 PreAimPose                                             (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// double                                  AimYaw                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  AimPitch                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FPoseLink*                       FullBody_Aiming_0                                      (Parm, OutParm, NoDestructor)

void IALI_ItemAnimLayers_C::FullBody_Aiming(const struct FPoseLink& PreAimPose, double AimYaw, double AimPitch, struct FPoseLink* FullBody_Aiming_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("ALI_ItemAnimLayers_C", "FullBody_Aiming");

	Params::ALI_ItemAnimLayers_C_FullBody_Aiming Parms{};

	Parms.PreAimPose = std::move(PreAimPose);
	Parms.AimYaw = AimYaw;
	Parms.AimPitch = AimPitch;

	AsUObject()->ProcessEvent(Func, &Parms);

	if (FullBody_Aiming_0 != nullptr)
		*FullBody_Aiming_0 = std::move(Parms.FullBody_Aiming_0);
}


// Function ALI_ItemAnimLayers.ALI_ItemAnimLayers_C.FullBody_CycleState
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       FullBody_CycleState_0                                  (Parm, OutParm, NoDestructor)

void IALI_ItemAnimLayers_C::FullBody_CycleState(struct FPoseLink* FullBody_CycleState_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("ALI_ItemAnimLayers_C", "FullBody_CycleState");

	Params::ALI_ItemAnimLayers_C_FullBody_CycleState Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (FullBody_CycleState_0 != nullptr)
		*FullBody_CycleState_0 = std::move(Parms.FullBody_CycleState_0);
}


// Function ALI_ItemAnimLayers.ALI_ItemAnimLayers_C.FullBody_Dash
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       FullBody_Dash_0                                        (Parm, OutParm, NoDestructor)

void IALI_ItemAnimLayers_C::FullBody_Dash(struct FPoseLink* FullBody_Dash_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("ALI_ItemAnimLayers_C", "FullBody_Dash");

	Params::ALI_ItemAnimLayers_C_FullBody_Dash Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (FullBody_Dash_0 != nullptr)
		*FullBody_Dash_0 = std::move(Parms.FullBody_Dash_0);
}


// Function ALI_ItemAnimLayers.ALI_ItemAnimLayers_C.FullBody_DoubleJump
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       FullBody_DoubleJump_0                                  (Parm, OutParm, NoDestructor)

void IALI_ItemAnimLayers_C::FullBody_DoubleJump(struct FPoseLink* FullBody_DoubleJump_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("ALI_ItemAnimLayers_C", "FullBody_DoubleJump");

	Params::ALI_ItemAnimLayers_C_FullBody_DoubleJump Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (FullBody_DoubleJump_0 != nullptr)
		*FullBody_DoubleJump_0 = std::move(Parms.FullBody_DoubleJump_0);
}


// Function ALI_ItemAnimLayers.ALI_ItemAnimLayers_C.FullBody_EntryState
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       FullBody_EntryState_0                                  (Parm, OutParm, NoDestructor)

void IALI_ItemAnimLayers_C::FullBody_EntryState(struct FPoseLink* FullBody_EntryState_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("ALI_ItemAnimLayers_C", "FullBody_EntryState");

	Params::ALI_ItemAnimLayers_C_FullBody_EntryState Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (FullBody_EntryState_0 != nullptr)
		*FullBody_EntryState_0 = std::move(Parms.FullBody_EntryState_0);
}


// Function ALI_ItemAnimLayers.ALI_ItemAnimLayers_C.FullBody_FallLandState
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       FullBody_FallLandState_0                               (Parm, OutParm, NoDestructor)

void IALI_ItemAnimLayers_C::FullBody_FallLandState(struct FPoseLink* FullBody_FallLandState_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("ALI_ItemAnimLayers_C", "FullBody_FallLandState");

	Params::ALI_ItemAnimLayers_C_FullBody_FallLandState Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (FullBody_FallLandState_0 != nullptr)
		*FullBody_FallLandState_0 = std::move(Parms.FullBody_FallLandState_0);
}


// Function ALI_ItemAnimLayers.ALI_ItemAnimLayers_C.FullBody_FallLoopState
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       FullBody_FallLoopState_0                               (Parm, OutParm, NoDestructor)

void IALI_ItemAnimLayers_C::FullBody_FallLoopState(struct FPoseLink* FullBody_FallLoopState_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("ALI_ItemAnimLayers_C", "FullBody_FallLoopState");

	Params::ALI_ItemAnimLayers_C_FullBody_FallLoopState Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (FullBody_FallLoopState_0 != nullptr)
		*FullBody_FallLoopState_0 = std::move(Parms.FullBody_FallLoopState_0);
}


// Function ALI_ItemAnimLayers.ALI_ItemAnimLayers_C.FullBody_IdleState
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       FullBody_IdleState_0                                   (Parm, OutParm, NoDestructor)

void IALI_ItemAnimLayers_C::FullBody_IdleState(struct FPoseLink* FullBody_IdleState_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("ALI_ItemAnimLayers_C", "FullBody_IdleState");

	Params::ALI_ItemAnimLayers_C_FullBody_IdleState Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (FullBody_IdleState_0 != nullptr)
		*FullBody_IdleState_0 = std::move(Parms.FullBody_IdleState_0);
}


// Function ALI_ItemAnimLayers.ALI_ItemAnimLayers_C.FullBody_JumpApexState
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       FullBody_JumpApexState_0                               (Parm, OutParm, NoDestructor)

void IALI_ItemAnimLayers_C::FullBody_JumpApexState(struct FPoseLink* FullBody_JumpApexState_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("ALI_ItemAnimLayers_C", "FullBody_JumpApexState");

	Params::ALI_ItemAnimLayers_C_FullBody_JumpApexState Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (FullBody_JumpApexState_0 != nullptr)
		*FullBody_JumpApexState_0 = std::move(Parms.FullBody_JumpApexState_0);
}


// Function ALI_ItemAnimLayers.ALI_ItemAnimLayers_C.FullBody_JumpStartLoopState
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       FullBody_JumpStartLoopState_0                          (Parm, OutParm, NoDestructor)

void IALI_ItemAnimLayers_C::FullBody_JumpStartLoopState(struct FPoseLink* FullBody_JumpStartLoopState_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("ALI_ItemAnimLayers_C", "FullBody_JumpStartLoopState");

	Params::ALI_ItemAnimLayers_C_FullBody_JumpStartLoopState Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (FullBody_JumpStartLoopState_0 != nullptr)
		*FullBody_JumpStartLoopState_0 = std::move(Parms.FullBody_JumpStartLoopState_0);
}


// Function ALI_ItemAnimLayers.ALI_ItemAnimLayers_C.FullBody_JumpStartState
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       FullBody_JumpStartState_0                              (Parm, OutParm, NoDestructor)

void IALI_ItemAnimLayers_C::FullBody_JumpStartState(struct FPoseLink* FullBody_JumpStartState_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("ALI_ItemAnimLayers_C", "FullBody_JumpStartState");

	Params::ALI_ItemAnimLayers_C_FullBody_JumpStartState Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (FullBody_JumpStartState_0 != nullptr)
		*FullBody_JumpStartState_0 = std::move(Parms.FullBody_JumpStartState_0);
}


// Function ALI_ItemAnimLayers.ALI_ItemAnimLayers_C.FullBody_PivotState
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       FullBody_PivotState_0                                  (Parm, OutParm, NoDestructor)

void IALI_ItemAnimLayers_C::FullBody_PivotState(struct FPoseLink* FullBody_PivotState_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("ALI_ItemAnimLayers_C", "FullBody_PivotState");

	Params::ALI_ItemAnimLayers_C_FullBody_PivotState Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (FullBody_PivotState_0 != nullptr)
		*FullBody_PivotState_0 = std::move(Parms.FullBody_PivotState_0);
}


// Function ALI_ItemAnimLayers.ALI_ItemAnimLayers_C.FullBody_SkeletalControls
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FPoseLink&                 InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink*                       FullBody_SkeletalControls_0                            (Parm, OutParm, NoDestructor)

void IALI_ItemAnimLayers_C::FullBody_SkeletalControls(const struct FPoseLink& InPose, struct FPoseLink* FullBody_SkeletalControls_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("ALI_ItemAnimLayers_C", "FullBody_SkeletalControls");

	Params::ALI_ItemAnimLayers_C_FullBody_SkeletalControls Parms{};

	Parms.InPose = std::move(InPose);

	AsUObject()->ProcessEvent(Func, &Parms);

	if (FullBody_SkeletalControls_0 != nullptr)
		*FullBody_SkeletalControls_0 = std::move(Parms.FullBody_SkeletalControls_0);
}


// Function ALI_ItemAnimLayers.ALI_ItemAnimLayers_C.FullBody_SlideInState
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       FullBody_SlideInState_0                                (Parm, OutParm, NoDestructor)

void IALI_ItemAnimLayers_C::FullBody_SlideInState(struct FPoseLink* FullBody_SlideInState_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("ALI_ItemAnimLayers_C", "FullBody_SlideInState");

	Params::ALI_ItemAnimLayers_C_FullBody_SlideInState Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (FullBody_SlideInState_0 != nullptr)
		*FullBody_SlideInState_0 = std::move(Parms.FullBody_SlideInState_0);
}


// Function ALI_ItemAnimLayers.ALI_ItemAnimLayers_C.FullBody_SlideLoopState
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       FullBody_SlideLoopState_0                              (Parm, OutParm, NoDestructor)

void IALI_ItemAnimLayers_C::FullBody_SlideLoopState(struct FPoseLink* FullBody_SlideLoopState_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("ALI_ItemAnimLayers_C", "FullBody_SlideLoopState");

	Params::ALI_ItemAnimLayers_C_FullBody_SlideLoopState Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (FullBody_SlideLoopState_0 != nullptr)
		*FullBody_SlideLoopState_0 = std::move(Parms.FullBody_SlideLoopState_0);
}


// Function ALI_ItemAnimLayers.ALI_ItemAnimLayers_C.FullBody_SlideOutState
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       FullBody_SlideOutState_0                               (Parm, OutParm, NoDestructor)

void IALI_ItemAnimLayers_C::FullBody_SlideOutState(struct FPoseLink* FullBody_SlideOutState_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("ALI_ItemAnimLayers_C", "FullBody_SlideOutState");

	Params::ALI_ItemAnimLayers_C_FullBody_SlideOutState Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (FullBody_SlideOutState_0 != nullptr)
		*FullBody_SlideOutState_0 = std::move(Parms.FullBody_SlideOutState_0);
}


// Function ALI_ItemAnimLayers.ALI_ItemAnimLayers_C.FullBody_StartState
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       FullBody_StartState_0                                  (Parm, OutParm, NoDestructor)

void IALI_ItemAnimLayers_C::FullBody_StartState(struct FPoseLink* FullBody_StartState_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("ALI_ItemAnimLayers_C", "FullBody_StartState");

	Params::ALI_ItemAnimLayers_C_FullBody_StartState Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (FullBody_StartState_0 != nullptr)
		*FullBody_StartState_0 = std::move(Parms.FullBody_StartState_0);
}


// Function ALI_ItemAnimLayers.ALI_ItemAnimLayers_C.FullBody_StopState
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       FullBody_StopState_0                                   (Parm, OutParm, NoDestructor)

void IALI_ItemAnimLayers_C::FullBody_StopState(struct FPoseLink* FullBody_StopState_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("ALI_ItemAnimLayers_C", "FullBody_StopState");

	Params::ALI_ItemAnimLayers_C_FullBody_StopState Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (FullBody_StopState_0 != nullptr)
		*FullBody_StopState_0 = std::move(Parms.FullBody_StopState_0);
}


// Function ALI_ItemAnimLayers.ALI_ItemAnimLayers_C.FullBodyAdditives
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       FullBodyAdditives_0                                    (Parm, OutParm, NoDestructor)

void IALI_ItemAnimLayers_C::FullBodyAdditives(struct FPoseLink* FullBodyAdditives_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("ALI_ItemAnimLayers_C", "FullBodyAdditives");

	Params::ALI_ItemAnimLayers_C_FullBodyAdditives Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (FullBodyAdditives_0 != nullptr)
		*FullBodyAdditives_0 = std::move(Parms.FullBodyAdditives_0);
}


// Function ALI_ItemAnimLayers.ALI_ItemAnimLayers_C.Head_FaceLayer
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       Head_FaceLayer_0                                       (Parm, OutParm, NoDestructor)

void IALI_ItemAnimLayers_C::Head_FaceLayer(struct FPoseLink* Head_FaceLayer_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("ALI_ItemAnimLayers_C", "Head_FaceLayer");

	Params::ALI_ItemAnimLayers_C_Head_FaceLayer Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (Head_FaceLayer_0 != nullptr)
		*Head_FaceLayer_0 = std::move(Parms.Head_FaceLayer_0);
}


// Function ALI_ItemAnimLayers.ALI_ItemAnimLayers_C.LeftHandPose_OverrideState
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FPoseLink&                 InputPose                                              (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink*                       LeftHandPose_OverrideState_0                           (Parm, OutParm, NoDestructor)

void IALI_ItemAnimLayers_C::LeftHandPose_OverrideState(const struct FPoseLink& InputPose, struct FPoseLink* LeftHandPose_OverrideState_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("ALI_ItemAnimLayers_C", "LeftHandPose_OverrideState");

	Params::ALI_ItemAnimLayers_C_LeftHandPose_OverrideState Parms{};

	Parms.InputPose = std::move(InputPose);

	AsUObject()->ProcessEvent(Func, &Parms);

	if (LeftHandPose_OverrideState_0 != nullptr)
		*LeftHandPose_OverrideState_0 = std::move(Parms.LeftHandPose_OverrideState_0);
}

}

