#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AuInventory

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "AuItems_classes.hpp"
#include "CoreUObject_classes.hpp"


namespace SDK
{

// Class AuInventory.AuInventoryBPF
// 0x0000 (0x0028 - 0x0028)
class UAuInventoryBPF final : public UBlueprintFunctionLibrary
{
public:
	static void ClearSlot(struct FAuItemSlot& Slot);
	static bool Equal(const struct FAuItemSlot& SlotOne, const struct FAuItemSlot& SlotTwo);
	static bool IsSlotValid(const struct FAuItemSlot& Slot);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AuInventoryBPF")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AuInventoryBPF")
	}
	static class UAuInventoryBPF* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAuInventoryBPF>();
	}
};
DUMPER7_ASSERTS_UAuInventoryBPF;

// Class AuInventory.AuInventoryComponent
// 0x0000 (0x09D0 - 0x09D0)
class UAuInventoryComponent : public UAuItemsComponent
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AuInventoryComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AuInventoryComponent")
	}
	static class UAuInventoryComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAuInventoryComponent>();
	}
};
DUMPER7_ASSERTS_UAuInventoryComponent;

// Class AuInventory.AuInventoryInterface
// 0x0000 (0x0000 - 0x0000)
class IAuInventoryInterface final
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AuInventoryInterface")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AuInventoryInterface")
	}
	static class IAuInventoryInterface* GetDefaultObj()
	{
		return GetDefaultObjImpl<IAuInventoryInterface>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_IAuInventoryInterface;

// Class AuInventory.AuPickupActorBase
// 0x0000 (0x03C8 - 0x03C8)
class AAuPickupActorBase final : public AAuItemPickupBase
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AuPickupActorBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AuPickupActorBase")
	}
	static class AAuPickupActorBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<AAuPickupActorBase>();
	}
};
DUMPER7_ASSERTS_AAuPickupActorBase;

}

