#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CameraShake_MovingWave

#include "Basic.hpp"

#include "EngineCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CameraShake_MovingWave.BP_CameraShake_MovingWave_C
// 0x0000 (0x01F0 - 0x01F0)
class UBP_CameraShake_MovingWave_C final : public ULegacyCameraShake
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CameraShake_MovingWave_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CameraShake_MovingWave_C")
	}
	static class UBP_CameraShake_MovingWave_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_CameraShake_MovingWave_C>();
	}
};
DUMPER7_ASSERTS_UBP_CameraShake_MovingWave_C;

}

