#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RangedTier2_PooledProjectile_SnotBig

#include "Basic.hpp"

#include "BP_RangedTier2_PooledProjectile_Snot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_RangedTier2_PooledProjectile_SnotBig.BP_RangedTier2_PooledProjectile_SnotBig_C
// 0x0000 (0x0380 - 0x0380)
class ABP_RangedTier2_PooledProjectile_SnotBig_C final : public ABP_RangedTier2_PooledProjectile_Snot_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_RangedTier2_PooledProjectile_SnotBig_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_RangedTier2_PooledProjectile_SnotBig_C")
	}
	static class ABP_RangedTier2_PooledProjectile_SnotBig_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_RangedTier2_PooledProjectile_SnotBig_C>();
	}
};
DUMPER7_ASSERTS_ABP_RangedTier2_PooledProjectile_SnotBig_C;

}

