#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Smelter

#include "Basic.hpp"

#include "BP_Smelter_classes.hpp"
#include "BP_Smelter_parameters.hpp"


namespace SDK
{

// Function BP_Smelter.BP_Smelter_C.ExecuteUbergraph_BP_Smelter
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Smelter_C::ExecuteUbergraph_BP_Smelter(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Smelter_C", "ExecuteUbergraph_BP_Smelter");

	Params::BP_Smelter_C_ExecuteUbergraph_BP_Smelter Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Smelter.BP_Smelter_C.OnBuildingStateChanged
// (Event, Public, BlueprintEvent)
// Parameters:
// ECrBuildingState                        InState                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Smelter_C::OnBuildingStateChanged(ECrBuildingState InState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Smelter_C", "OnBuildingStateChanged");

	Params::BP_Smelter_C_OnBuildingStateChanged Parms{};

	Parms.InState = InState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Smelter.BP_Smelter_C.SetupSkeletalMesh
// (Event, Public, BlueprintEvent)

void ABP_Smelter_C::SetupSkeletalMesh()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Smelter_C", "SetupSkeletalMesh");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Smelter.BP_Smelter_C.Get Meshes
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class USceneComponent*                  Static_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class USceneComponent*                  Animated_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// TArray<class UMeshComponent*>*          NewParam                                               (Parm, OutParm, ContainsInstancedReference)

void ABP_Smelter_C::Get_Meshes(class USceneComponent* Static_0, class USceneComponent* Animated_0, TArray<class UMeshComponent*>* NewParam) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Smelter_C", "Get Meshes");

	Params::BP_Smelter_C_Get_Meshes Parms{};

	Parms.Static_0 = Static_0;
	Parms.Animated_0 = Animated_0;

	UObject::ProcessEvent(Func, &Parms);

	if (NewParam != nullptr)
		*NewParam = std::move(Parms.NewParam);
}

}

