#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TurretTier2

#include "Basic.hpp"

#include "BP_TurretTier2_classes.hpp"
#include "BP_TurretTier2_parameters.hpp"


namespace SDK
{

// Function BP_TurretTier2.BP_TurretTier2_C.BP_OnInventoryChanged
// (Event, Protected, BlueprintEvent)

void ABP_TurretTier2_C::BP_OnInventoryChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TurretTier2_C", "BP_OnInventoryChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TurretTier2.BP_TurretTier2_C.CosmeticHit
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FHitResult&                InHit                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABP_TurretTier2_C::CosmeticHit(const struct FHitResult& InHit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TurretTier2_C", "CosmeticHit");

	Params::BP_TurretTier2_C_CosmeticHit Parms{};

	Parms.InHit = std::move(InHit);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TurretTier2.BP_TurretTier2_C.CosmeticTurretMalfunctionEnded
// (Event, Public, BlueprintEvent)

void ABP_TurretTier2_C::CosmeticTurretMalfunctionEnded()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TurretTier2_C", "CosmeticTurretMalfunctionEnded");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TurretTier2.BP_TurretTier2_C.CosmeticTurretMalfunctionStarted
// (Event, Public, BlueprintEvent)

void ABP_TurretTier2_C::CosmeticTurretMalfunctionStarted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TurretTier2_C", "CosmeticTurretMalfunctionStarted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TurretTier2.BP_TurretTier2_C.ExecuteUbergraph_BP_TurretTier2
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TurretTier2_C::ExecuteUbergraph_BP_TurretTier2(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TurretTier2_C", "ExecuteUbergraph_BP_TurretTier2");

	Params::BP_TurretTier2_C_ExecuteUbergraph_BP_TurretTier2 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TurretTier2.BP_TurretTier2_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_TurretTier2_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TurretTier2_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TurretTier2.BP_TurretTier2_C.Timeline__FinishedFunc
// (BlueprintEvent)

void ABP_TurretTier2_C::Timeline__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TurretTier2_C", "Timeline__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TurretTier2.BP_TurretTier2_C.Timeline__UpdateFunc
// (BlueprintEvent)

void ABP_TurretTier2_C::Timeline__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TurretTier2_C", "Timeline__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TurretTier2.BP_TurretTier2_C.UpdateAmmoCounter
// (BlueprintCallable, BlueprintEvent)

void ABP_TurretTier2_C::UpdateAmmoCounter()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TurretTier2_C", "UpdateAmmoCounter");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TurretTier2.BP_TurretTier2_C.UpdateCosmeticsBasedOnAttackDirection
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FVector&                   OutCurrentAttackDirection                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TurretTier2_C::UpdateCosmeticsBasedOnAttackDirection(const struct FVector& OutCurrentAttackDirection)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TurretTier2_C", "UpdateCosmeticsBasedOnAttackDirection");

	Params::BP_TurretTier2_C_UpdateCosmeticsBasedOnAttackDirection Parms{};

	Parms.OutCurrentAttackDirection = std::move(OutCurrentAttackDirection);

	UObject::ProcessEvent(Func, &Parms);
}

}

