#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_WaveSmelter

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_WaveSmelter.BP_WaveSmelter_C.Get Meshes
// 0x0010 (0x0010 - 0x0000)
struct BP_WaveSmelter_C_Get_Meshes final
{
public:
	class USceneComponent*                        Static;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Animated;                                          // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_WaveSmelter_C_Get_Meshes;

// Function BP_WaveSmelter.BP_WaveSmelter_C.GetBuildingMeshes
// 0x0018 (0x0018 - 0x0000)
struct BP_WaveSmelter_C_GetBuildingMeshes final
{
public:
	class UMeshComponent*                         MainBody;                                          // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<class UMeshComponent*>                 AdditionalMeshes;                                  // 0x0008(0x0010)(Parm, OutParm, ContainsInstancedReference)
};
DUMPER7_ASSERTS_BP_WaveSmelter_C_GetBuildingMeshes;

}

