#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPW_ResolutionMenu

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BPW_List_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BPW_ResolutionMenu.BPW_ResolutionMenu_C
// 0x0010 (0x0410 - 0x0400)
class UBPW_ResolutionMenu_C final : public UBPW_List_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BPW_ResolutionMenu_C;               // 0x0400(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UDataTable*                             Resolutions;                                       // 0x0408(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

public:
	void SelectionChanged_Event_0();
	void PreConstruct(bool IsDesignTime);
	void InitResolution(class UGameUserSettings* GameUserSettings);
	void ExecuteUbergraph_BPW_ResolutionMenu(int32 EntryPoint);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPW_ResolutionMenu_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPW_ResolutionMenu_C")
	}
	static class UBPW_ResolutionMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPW_ResolutionMenu_C>();
	}
};
DUMPER7_ASSERTS_UBPW_ResolutionMenu_C;

}

