#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FAnimStruct_CardinalDirections

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct FAnimStruct_CardinalDirections.FAnimStruct_CardinalDirections
// 0x0020 (0x0020 - 0x0000)
struct FFAnimStruct_CardinalDirections final
{
public:
	class UAnimSequence*                          Forward_12_1A70C7D74223ECC610B8E0B7CEA98DEB;       // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAnimSequence*                          Backward_13_CF59C8D94DCBEFE2AF1A66ADEB6EE2AE;      // 0x0008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAnimSequence*                          Left_14_A3A742054C2C89979F0DD685FCC7ED04;          // 0x0010(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAnimSequence*                          Right_15_77966216476637C79AA24E9C31ACA6C4;         // 0x0018(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FFAnimStruct_CardinalDirections;

}

