#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_CamEffect_ShieldInfectionDamage

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Chimera_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_CamEffect_ShieldInfectionDamage.GE_CamEffect_ShieldInfectionDamage_C
// 0x0008 (0x0AB0 - 0x0AA8)
class UGE_CamEffect_ShieldInfectionDamage_C final : public UCrCameraGameplayEffect
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0AA8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GE_CamEffect_ShieldInfectionDamage(int32 EntryPoint);
	void OnAttributeChanged_2CEB6F144A668C2237F5569FF3F48525(const struct FGameplayAttribute& Attribute, float NewValue, float OldValue);
	void OnInitialized(class UAbilitySystemComponent* AbilitySystemComponent, TSubclassOf<class UGameplayEffect> GameplayEffect, class USceneComponent* OwnerRootComponent);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_CamEffect_ShieldInfectionDamage_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_CamEffect_ShieldInfectionDamage_C")
	}
	static class UGE_CamEffect_ShieldInfectionDamage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_CamEffect_ShieldInfectionDamage_C>();
	}
};
DUMPER7_ASSERTS_UGE_CamEffect_ShieldInfectionDamage_C;

}

