#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: I_ConsumableStatsGemT3

#include "Basic.hpp"

#include "Chimera_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass I_ConsumableStatsGemT3.I_ConsumableStatsGemT3_C
// 0x0000 (0x0420 - 0x0420)
class UI_ConsumableStatsGemT3_C final : public UCrGemItemData
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("I_ConsumableStatsGemT3_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"I_ConsumableStatsGemT3_C")
	}
	static class UI_ConsumableStatsGemT3_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UI_ConsumableStatsGemT3_C>();
	}
};
DUMPER7_ASSERTS_UI_ConsumableStatsGemT3_C;

}

