#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: I_Rifle_Mod_StockStable

#include "Basic.hpp"

#include "Chimera_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass I_Rifle_Mod_StockStable.I_Rifle_Mod_StockStable_C
// 0x0000 (0x0410 - 0x0410)
class UI_Rifle_Mod_StockStable_C final : public UCrWeaponModBlueprintItemBase
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("I_Rifle_Mod_StockStable_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"I_Rifle_Mod_StockStable_C")
	}
	static class UI_Rifle_Mod_StockStable_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UI_Rifle_Mod_StockStable_C>();
	}
};
DUMPER7_ASSERTS_UI_Rifle_Mod_StockStable_C;

}

