#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PC_PlayerControllerBase

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Chimera_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PC_PlayerControllerBase.PC_PlayerControllerBase_C
// 0x0010 (0x1120 - 0x1110)
class APC_PlayerControllerBase_C final : public ACrPlayerControllerBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x1110(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	double                                        MinPitch;                                          // 0x1118(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ReceiveBeginPlay();
	void OnServerExecuteConsoleCommand();
	void K2_ShowProfessionMenu();
	void InpActEvt_K_K2Node_InputDebugKeyEvent_0(const struct FKey& Key, const struct FInputActionValue& ActionValue);
	void ExecuteUbergraph_PC_PlayerControllerBase(int32 EntryPoint);
	void cheat_Teleport2player(int32 PlayerId);
	bool CanInputKeyBePassedFromUIOnlyMode(const struct FKey& Key);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PC_PlayerControllerBase_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PC_PlayerControllerBase_C")
	}
	static class APC_PlayerControllerBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APC_PlayerControllerBase_C>();
	}
};
DUMPER7_ASSERTS_APC_PlayerControllerBase_C;

}

