#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_QuickUseEntry

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ChimeraUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_QuickUseEntry.WBP_QuickUseEntry_C
// 0x0010 (0x03D0 - 0x03C0)
class UWBP_QuickUseEntry_C final : public UCrUW_QuickUseEntry
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UTextBlock*                             Index_0;                                           // 0x03C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void OnDataRefresh(int32 Param_Index_0);
	void ExecuteUbergraph_WBP_QuickUseEntry(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_QuickUseEntry_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_QuickUseEntry_C")
	}
	static class UWBP_QuickUseEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_QuickUseEntry_C>();
	}
};
DUMPER7_ASSERTS_UWBP_QuickUseEntry_C;

}

