#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DroneJunction

#include "Basic.hpp"

#include "Chimera_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DroneJunction.BP_DroneJunction_C
// 0x0018 (0x0650 - 0x0638)
class ABP_DroneJunction_C final : public ACrDronePathPoint
{
public:
	class UStaticMeshComponent*                   PlacementHelper;                                   // 0x0638(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   MainMesh;                                          // 0x0640(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAuActorPlacementSocketsComponent*      AuActorPlacementSockets;                           // 0x0648(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DroneJunction_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DroneJunction_C")
	}
	static class ABP_DroneJunction_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DroneJunction_C>();
	}
};
DUMPER7_ASSERTS_ABP_DroneJunction_C;

}

