#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PlantGrower

#include "Basic.hpp"

#include "BP_PlantGrower_classes.hpp"
#include "BP_PlantGrower_parameters.hpp"


namespace SDK
{

// Function BP_PlantGrower.BP_PlantGrower_C.ExecuteUbergraph_BP_PlantGrower
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PlantGrower_C::ExecuteUbergraph_BP_PlantGrower(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlantGrower_C", "ExecuteUbergraph_BP_PlantGrower");

	Params::BP_PlantGrower_C_ExecuteUbergraph_BP_PlantGrower Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PlantGrower.BP_PlantGrower_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_PlantGrower_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlantGrower_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PlantGrower.BP_PlantGrower_C.Timeline__FinishedFunc
// (BlueprintEvent)

void ABP_PlantGrower_C::Timeline__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlantGrower_C", "Timeline__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PlantGrower.BP_PlantGrower_C.Timeline__UpdateFunc
// (BlueprintEvent)

void ABP_PlantGrower_C::Timeline__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlantGrower_C", "Timeline__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}

}

