#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Ranged_Tier3_Actor_AiController

#include "Basic.hpp"

#include "BP_Ranged_Tier3_Actor_AiController_classes.hpp"
#include "BP_Ranged_Tier3_Actor_AiController_parameters.hpp"


namespace SDK
{

// Function BP_Ranged_Tier3_Actor_AiController.BP_Ranged_Tier3_Actor_AiController_C.ExecuteUbergraph_BP_Ranged_Tier3_Actor_AiController
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Ranged_Tier3_Actor_AiController_C::ExecuteUbergraph_BP_Ranged_Tier3_Actor_AiController(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ranged_Tier3_Actor_AiController_C", "ExecuteUbergraph_BP_Ranged_Tier3_Actor_AiController");

	Params::BP_Ranged_Tier3_Actor_AiController_C_ExecuteUbergraph_BP_Ranged_Tier3_Actor_AiController Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Ranged_Tier3_Actor_AiController.BP_Ranged_Tier3_Actor_AiController_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Ranged_Tier3_Actor_AiController_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ranged_Tier3_Actor_AiController_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

