#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TemperatureDamageExecution

#include "Basic.hpp"

#include "Chimera_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_TemperatureDamageExecution.BP_TemperatureDamageExecution_C
// 0x0000 (0x00F0 - 0x00F0)
class UBP_TemperatureDamageExecution_C final : public UCrAttributeDamageExecution
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_TemperatureDamageExecution_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TemperatureDamageExecution_C")
	}
	static class UBP_TemperatureDamageExecution_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_TemperatureDamageExecution_C>();
	}
};
DUMPER7_ASSERTS_UBP_TemperatureDamageExecution_C;

}

