#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPW_Stat

#include "Basic.hpp"

#include "BPW_Stat_classes.hpp"
#include "BPW_Stat_parameters.hpp"


namespace SDK
{

// Function BPW_Stat.BPW_Stat_C.UpdateValue
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm)
// const struct FLinearColor&              Color                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPW_Stat_C::UpdateValue(const class FText& Value, const struct FLinearColor& Color)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_Stat_C", "UpdateValue");

	Params::BPW_Stat_C_UpdateValue Parms{};

	Parms.Value = std::move(Value);
	Parms.Color = std::move(Color);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPW_Stat.BPW_Stat_C.UpdateLabel
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      Label                                                  (BlueprintVisible, BlueprintReadOnly, Parm)

void UBPW_Stat_C::UpdateLabel(const class FText& Label)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_Stat_C", "UpdateLabel");

	Params::BPW_Stat_C_UpdateLabel Parms{};

	Parms.Label = std::move(Label);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPW_Stat.BPW_Stat_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPW_Stat_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_Stat_C", "PreConstruct");

	Params::BPW_Stat_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPW_Stat.BPW_Stat_C.ExecuteUbergraph_BPW_Stat
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPW_Stat_C::ExecuteUbergraph_BPW_Stat(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_Stat_C", "ExecuteUbergraph_BPW_Stat");

	Params::BPW_Stat_C_ExecuteUbergraph_BPW_Stat Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

