#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTService_Ranged_Tier1_LOD0_UpdateAfterShotFiredPosition

#include "Basic.hpp"

#include "AIModule_structs.hpp"
#include "AIModule_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BTService_Ranged_Tier1_LOD0_UpdateAfterShotFiredPosition.BTService_Ranged_Tier1_LOD0_UpdateAfterShotFiredPosition_C
// 0x0038 (0x00D0 - 0x0098)
class UBTService_Ranged_Tier1_LOD0_UpdateAfterShotFiredPosition_C final : public UBTService_BlueprintBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0098(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	double                                        Walk_Away_Distance;                                // 0x00A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FBlackboardKeySelector                 Out_Calcualted_Position;                           // 0x00A8(0x0028)(Edit, BlueprintVisible)

public:
	void ExecuteUbergraph_BTService_Ranged_Tier1_LOD0_UpdateAfterShotFiredPosition(int32 EntryPoint);
	void ReceiveActivationAI(class AAIController* OwnerController, class APawn* ControlledPawn);
	void UpdateAfterShotFiredPosition(class AActor* Pawn, class AAIController* Controller);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BTService_Ranged_Tier1_LOD0_UpdateAfterShotFiredPosition_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BTService_Ranged_Tier1_LOD0_UpdateAfterShotFiredPosition_C")
	}
	static class UBTService_Ranged_Tier1_LOD0_UpdateAfterShotFiredPosition_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBTService_Ranged_Tier1_LOD0_UpdateAfterShotFiredPosition_C>();
	}
};
DUMPER7_ASSERTS_UBTService_Ranged_Tier1_LOD0_UpdateAfterShotFiredPosition_C;

}

