#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: I_AquaBar

#include "Basic.hpp"

#include "Chimera_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass I_AquaBar.I_AquaBar_C
// 0x0000 (0x0420 - 0x0420)
class UI_AquaBar_C final : public UCrEdibleItemBase
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("I_AquaBar_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"I_AquaBar_C")
	}
	static class UI_AquaBar_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UI_AquaBar_C>();
	}
};
DUMPER7_ASSERTS_UI_AquaBar_C;

}

