#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: I_SelenianCorpReputation

#include "Basic.hpp"

#include "Chimera_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass I_SelenianCorpReputation.I_SelenianCorpReputation_C
// 0x0000 (0x0410 - 0x0410)
class UI_SelenianCorpReputation_C final : public UCrReputationItemData
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("I_SelenianCorpReputation_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"I_SelenianCorpReputation_C")
	}
	static class UI_SelenianCorpReputation_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UI_SelenianCorpReputation_C>();
	}
};
DUMPER7_ASSERTS_UI_SelenianCorpReputation_C;

}

