#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MiningTool_Progress

#include "Basic.hpp"

#include "WBP_MiningTool_Progress_classes.hpp"
#include "WBP_MiningTool_Progress_parameters.hpp"


namespace SDK
{

// Function WBP_MiningTool_Progress.WBP_MiningTool_Progress_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_MiningTool_Progress_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MiningTool_Progress_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MiningTool_Progress.WBP_MiningTool_Progress_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_MiningTool_Progress_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MiningTool_Progress_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MiningTool_Progress.WBP_MiningTool_Progress_C.ExecuteUbergraph_WBP_MiningTool_Progress
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MiningTool_Progress_C::ExecuteUbergraph_WBP_MiningTool_Progress(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MiningTool_Progress_C", "ExecuteUbergraph_WBP_MiningTool_Progress");

	Params::WBP_MiningTool_Progress_C_ExecuteUbergraph_WBP_MiningTool_Progress Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

